/**
 * Obsidian Circle geographic factor table — GENERATED DATA, PROTOCOL CONSTANT.
 *
 * This table is part of the protocol: every node derives identical initial GLVs
 * from it. It is shipped inside obsidian-core and never fetched at runtime, so
 * a network outage, an API change or a compromised CDN can never reprice land.
 *
 * Changing this file changes land pricing and therefore requires a protocol
 * version bump (it is included in PARAMS_HASH revocation checks and in the
 * release checksums).
 *
 * Fields per country:
 *   populationM     population in millions (published reference values)
 *   economy         economic activity index, 0-100
 *   infrastructure  infrastructure index, 0-100
 *   tourism         tourism index, 0-100
 *   significance    global significance index, 0-100
 *   divisions       ISO 3166-2 first-level divisions with optional weights
 *                   (percent, 100 = neutral) for tourism/economic concentration
 */

export interface RawDivision {
  id: string;
  name: string;
  /** Percent weight applied to the country GLV (100 = neutral). */
  weight?: number;
}

export interface RawCountry {
  code: string;
  name: string;
  continent: string;
  populationM: number;
  economy: number;
  infrastructure: number;
  tourism: number;
  significance: number;
  divisions?: RawDivision[];
}

export interface RawGeography {
  version: string;
  countries: RawCountry[];
}

export const GEOGRAPHY: RawGeography = {
  version: "1.0.0",
  countries: [
    { code: "AE", name: "United Arab Emirates", continent: "Asia", populationM: 10, economy: 92, infrastructure: 96, tourism: 95, significance: 85, divisions: [{ id: "AE-AZ", name: "Abu Dhabi", weight: 170 }, { id: "AE-DU", name: "Dubai", weight: 200 }, { id: "AE-SH", name: "Sharjah", weight: 140 }, { id: "AE-AJ", name: "Ajman" }, { id: "AE-UQ", name: "Umm Al Quwain" }, { id: "AE-RK", name: "Ras Al Khaimah", weight: 135 }, { id: "AE-FU", name: "Fujairah", weight: 130 }] },
    { code: "AM", name: "Armenia", continent: "Asia", populationM: 3, economy: 45, infrastructure: 52, tourism: 72, significance: 40, divisions: [{ id: "AM-ER", name: "Yerevan", weight: 140 }, { id: "AM-AG", name: "Aragatsotn" }, { id: "AM-AR", name: "Ararat" }, { id: "AM-AV", name: "Armavir" }, { id: "AM-GR", name: "Gegharkunik" }, { id: "AM-KT", name: "Kotayk" }, { id: "AM-LO", name: "Lori" }, { id: "AM-SH", name: "Shirak" }, { id: "AM-SU", name: "Syunik" }, { id: "AM-TV", name: "Tavush" }, { id: "AM-VD", name: "Vayots Dzor" }] },
    { code: "AO", name: "Angola", continent: "Africa", populationM: 36, economy: 38, infrastructure: 32, tourism: 60, significance: 42, divisions: [{ id: "AO-LUA", name: "Luanda", weight: 145 }, { id: "AO-BGO", name: "Bengo" }, { id: "AO-BGU", name: "Benguela" }, { id: "AO-BIE", name: "Bie" }, { id: "AO-CAB", name: "Cabinda" }, { id: "AO-CCU", name: "Cuando Cubango" }, { id: "AO-CNN", name: "Cunene" }, { id: "AO-CNO", name: "Cuanza Norte" }, { id: "AO-CUS", name: "Cuanza Sul" }, { id: "AO-HUA", name: "Huambo" }, { id: "AO-HUI", name: "Huila" }, { id: "AO-LNO", name: "Lunda Norte" }, { id: "AO-LSU", name: "Lunda Sul" }, { id: "AO-MAL", name: "Malange" }, { id: "AO-MOX", name: "Moxico" }, { id: "AO-NAM", name: "Namibe" }, { id: "AO-UIG", name: "Uige" }, { id: "AO-ZAI", name: "Zaire" }] },
    { code: "AR", name: "Argentina", continent: "South America", populationM: 46, economy: 55, infrastructure: 62, tourism: 75, significance: 60, divisions: [{ id: "AR-C", name: "Ciudad de Buenos Aires", weight: 150 }, { id: "AR-B", name: "Buenos Aires", weight: 105 }, { id: "AR-X", name: "Cordoba" }, { id: "AR-S", name: "Santa Fe" }, { id: "AR-M", name: "Mendoza", weight: 110 }, { id: "AR-T", name: "Tucuman" }, { id: "AR-A", name: "Salta" }, { id: "AR-Q", name: "Neuquen" }, { id: "AR-R", name: "Rio Negro" }, { id: "AR-U", name: "Chubut" }, { id: "AR-Z", name: "Santa Cruz" }, { id: "AR-E", name: "Entre Rios" }, { id: "AR-W", name: "Corrientes" }, { id: "AR-H", name: "Chaco" }, { id: "AR-K", name: "Catamarca" }, { id: "AR-J", name: "San Juan" }, { id: "AR-D", name: "San Luis" }, { id: "AR-L", name: "La Pampa" }, { id: "AR-F", name: "La Rioja" }, { id: "AR-G", name: "Santiago del Estero" }, { id: "AR-N", name: "Misiones" }, { id: "AR-P", name: "Formosa" }, { id: "AR-Y", name: "Jujuy" }] },
    { code: "AT", name: "Austria", continent: "Europe", populationM: 9, economy: 82, infrastructure: 92, tourism: 92, significance: 72, divisions: [{ id: "AT-9", name: "Vienna", weight: 175 }, { id: "AT-5", name: "Salzburg", weight: 155 }, { id: "AT-7", name: "Tyrol", weight: 160 }, { id: "AT-4", name: "Upper Austria" }, { id: "AT-3", name: "Lower Austria" }, { id: "AT-6", name: "Styria" }, { id: "AT-2", name: "Carinthia", weight: 140 }, { id: "AT-8", name: "Vorarlberg" }, { id: "AT-1", name: "Burgenland" }] },
    { code: "AU", name: "Australia", continent: "Oceania", populationM: 26, economy: 92, infrastructure: 92, tourism: 82, significance: 70, divisions: [{ id: "AU-NSW", name: "New South Wales", weight: 140 }, { id: "AU-VIC", name: "Victoria", weight: 130 }, { id: "AU-QLD", name: "Queensland", weight: 115 }, { id: "AU-WA", name: "Western Australia" }, { id: "AU-SA", name: "South Australia" }, { id: "AU-TAS", name: "Tasmania", weight: 115 }, { id: "AU-ACT", name: "Australian Capital Territory" }, { id: "AU-NT", name: "Northern Territory" }] },
    { code: "AZ", name: "Azerbaijan", continent: "Asia", populationM: 10, economy: 55, infrastructure: 62, tourism: 72, significance: 48, divisions: [{ id: "AZ-BA", name: "Baku", weight: 150 }, { id: "AZ-GA", name: "Ganja" }, { id: "AZ-SM", name: "Sumqayit" }, { id: "AZ-AB", name: "Absheron" }, { id: "AZ-NA", name: "Nakhchivan" }, { id: "AZ-MI", name: "Mingachevir" }, { id: "AZ-SA", name: "Shaki", weight: 135 }, { id: "AZ-LA", name: "Lankaran" }] },
    { code: "BB", name: "Barbados", continent: "North America", populationM: 0, economy: 55, infrastructure: 62, tourism: 85, significance: 42, divisions: [{ id: "BB-01", name: "Christ Church" }, { id: "BB-02", name: "Saint Andrew" }, { id: "BB-03", name: "Saint George" }, { id: "BB-04", name: "Saint James", weight: 140 }, { id: "BB-05", name: "Saint John" }, { id: "BB-06", name: "Saint Joseph" }, { id: "BB-07", name: "Saint Lucy" }, { id: "BB-08", name: "Saint Michael", weight: 140 }, { id: "BB-09", name: "Saint Peter" }, { id: "BB-10", name: "Saint Philip" }, { id: "BB-11", name: "Saint Thomas" }] },
    { code: "BD", name: "Bangladesh", continent: "Asia", populationM: 173, economy: 42, infrastructure: 35, tourism: 50, significance: 52, divisions: [{ id: "BD-C", name: "Dhaka", weight: 150 }, { id: "BD-B", name: "Chittagong" }, { id: "BD-D", name: "Khulna" }, { id: "BD-E", name: "Rajshahi" }, { id: "BD-F", name: "Rangpur" }, { id: "BD-G", name: "Sylhet" }, { id: "BD-A", name: "Barisal" }, { id: "BD-H", name: "Mymensingh" }] },
    { code: "BE", name: "Belgium", continent: "Europe", populationM: 12, economy: 78, infrastructure: 90, tourism: 80, significance: 72, divisions: [{ id: "BE-BRU", name: "Brussels", weight: 160 }, { id: "BE-VAN", name: "Antwerp" }, { id: "BE-VOV", name: "East Flanders" }, { id: "BE-VWV", name: "West Flanders" }, { id: "BE-WBR", name: "Walloon Brabant" }, { id: "BE-WLG", name: "Liege" }, { id: "BE-WHT", name: "Hainaut" }, { id: "BE-WNA", name: "Namur" }, { id: "BE-WLX", name: "Luxembourg" }, { id: "BE-VLI", name: "Limburg" }, { id: "BE-VBR", name: "Flemish Brabant" }] },
    { code: "BG", name: "Bulgaria", continent: "Europe", populationM: 6, economy: 52, infrastructure: 58, tourism: 82, significance: 48, divisions: [{ id: "BG-22", name: "Sofia", weight: 145 }, { id: "BG-01", name: "Blagoevgrad" }, { id: "BG-02", name: "Burgas", weight: 130 }, { id: "BG-03", name: "Varna", weight: 135 }, { id: "BG-04", name: "Veliko Tarnovo" }, { id: "BG-05", name: "Vidin" }, { id: "BG-06", name: "Vratsa" }, { id: "BG-07", name: "Gabrovo" }, { id: "BG-08", name: "Dobrich" }, { id: "BG-09", name: "Kardzhali" }, { id: "BG-10", name: "Kyustendil" }, { id: "BG-11", name: "Lovech" }, { id: "BG-12", name: "Montana" }, { id: "BG-13", name: "Pazardzhik" }, { id: "BG-14", name: "Pernik" }, { id: "BG-15", name: "Pleven" }, { id: "BG-16", name: "Plovdiv" }, { id: "BG-17", name: "Razgrad" }, { id: "BG-18", name: "Ruse" }, { id: "BG-19", name: "Silistra" }, { id: "BG-20", name: "Sliven" }, { id: "BG-21", name: "Smolyan" }, { id: "BG-23", name: "Sofia Province" }, { id: "BG-24", name: "Stara Zagora" }, { id: "BG-25", name: "Targovishte" }, { id: "BG-26", name: "Haskovo" }, { id: "BG-27", name: "Shumen" }, { id: "BG-28", name: "Yambol" }] },
    { code: "BO", name: "Bolivia", continent: "South America", populationM: 12, economy: 42, infrastructure: 42, tourism: 72, significance: 45, divisions: [{ id: "BO-L", name: "La Paz", weight: 145 }, { id: "BO-C", name: "Cochabamba" }, { id: "BO-S", name: "Santa Cruz" }, { id: "BO-H", name: "Chuquisaca" }, { id: "BO-T", name: "Tarija" }, { id: "BO-O", name: "Oruro" }, { id: "BO-P", name: "Potosi" }, { id: "BO-N", name: "Pando" }, { id: "BO-B", name: "Beni" }] },
    { code: "BR", name: "Brazil", continent: "South America", populationM: 216, economy: 68, infrastructure: 55, tourism: 78, significance: 72, divisions: [{ id: "BR-SP", name: "Sao Paulo", weight: 160 }, { id: "BR-RJ", name: "Rio de Janeiro", weight: 150 }, { id: "BR-MG", name: "Minas Gerais", weight: 110 }, { id: "BR-BA", name: "Bahia" }, { id: "BR-RS", name: "Rio Grande do Sul" }, { id: "BR-PR", name: "Parana" }, { id: "BR-PE", name: "Pernambuco" }, { id: "BR-CE", name: "Ceara" }, { id: "BR-PA", name: "Para" }, { id: "BR-SC", name: "Santa Catarina" }, { id: "BR-GO", name: "Goias" }, { id: "BR-MA", name: "Maranhao" }, { id: "BR-AM", name: "Amazonas", weight: 105 }, { id: "BR-ES", name: "Espirito Santo" }, { id: "BR-PB", name: "Paraiba" }, { id: "BR-RN", name: "Rio Grande do Norte" }, { id: "BR-AL", name: "Alagoas" }, { id: "BR-PI", name: "Piaui" }, { id: "BR-MT", name: "Mato Grosso" }, { id: "BR-MS", name: "Mato Grosso do Sul" }, { id: "BR-DF", name: "Distrito Federal", weight: 130 }, { id: "BR-SE", name: "Sergipe" }, { id: "BR-TO", name: "Tocantins" }, { id: "BR-RO", name: "Rondonia" }, { id: "BR-AC", name: "Acre" }, { id: "BR-AP", name: "Amapa" }, { id: "BR-RR", name: "Roraima" }] },
    { code: "BS", name: "Bahamas", continent: "North America", populationM: 0, economy: 60, infrastructure: 65, tourism: 90, significance: 45, divisions: [{ id: "BS-NP", name: "New Providence", weight: 140 }, { id: "BS-FP", name: "Freeport", weight: 140 }, { id: "BS-EX", name: "Exuma" }, { id: "BS-AB", name: "Abaco" }, { id: "BS-AN", name: "Andros" }, { id: "BS-EL", name: "Eleuthera" }, { id: "BS-RS", name: "Rum Cay" }] },
    { code: "BY", name: "Belarus", continent: "Europe", populationM: 9, economy: 52, infrastructure: 62, tourism: 55, significance: 48, divisions: [{ id: "BY-HM", name: "Minsk", weight: 145 }, { id: "BY-MI", name: "Minsk Region" }, { id: "BY-HO", name: "Gomel" }, { id: "BY-VI", name: "Vitebsk" }, { id: "BY-BR", name: "Brest" }, { id: "BY-HR", name: "Grodno" }, { id: "BY-MA", name: "Mogilev" }] },
    { code: "CA", name: "Canada", continent: "North America", populationM: 40, economy: 85, infrastructure: 88, tourism: 80, significance: 85, divisions: [{ id: "CA-ON", name: "Ontario", weight: 150 }, { id: "CA-QC", name: "Quebec", weight: 120 }, { id: "CA-BC", name: "British Columbia", weight: 130 }, { id: "CA-AB", name: "Alberta", weight: 115 }, { id: "CA-MB", name: "Manitoba" }, { id: "CA-SK", name: "Saskatchewan" }, { id: "CA-NS", name: "Nova Scotia" }, { id: "CA-NB", name: "New Brunswick" }, { id: "CA-NL", name: "Newfoundland and Labrador" }, { id: "CA-PE", name: "Prince Edward Island" }, { id: "CA-NT", name: "Northwest Territories" }, { id: "CA-YT", name: "Yukon" }, { id: "CA-NU", name: "Nunavut" }] },
    { code: "CH", name: "Switzerland", continent: "Europe", populationM: 9, economy: 98, infrastructure: 98, tourism: 90, significance: 85, divisions: [{ id: "CH-ZH", name: "Zurich", weight: 175 }, { id: "CH-GE", name: "Geneva", weight: 180 }, { id: "CH-VD", name: "Vaud", weight: 145 }, { id: "CH-BE", name: "Bern" }, { id: "CH-TI", name: "Ticino", weight: 140 }, { id: "CH-BS", name: "Basel-Stadt" }, { id: "CH-LU", name: "Lucerne" }, { id: "CH-ZG", name: "Zug", weight: 165 }, { id: "CH-SG", name: "St. Gallen" }, { id: "CH-VS", name: "Valais", weight: 145 }, { id: "CH-GR", name: "Graubunden" }, { id: "CH-AG", name: "Aargau" }] },
    { code: "CI", name: "Cote d'Ivoire", continent: "Africa", populationM: 29, economy: 45, infrastructure: 45, tourism: 72, significance: 45, divisions: [{ id: "CI-AB", name: "Abidjan", weight: 145 }, { id: "CI-BS", name: "Bas-Sassandra" }, { id: "CI-CM", name: "Comoe" }, { id: "CI-DN", name: "Denguele" }, { id: "CI-GD", name: "Goh-Djiboua" }, { id: "CI-LC", name: "Lacs" }, { id: "CI-LG", name: "Lagunes" }, { id: "CI-MG", name: "Montagnes" }, { id: "CI-SM", name: "Sassandra-Marahoue" }, { id: "CI-SV", name: "Savanes" }, { id: "CI-VB", name: "Vallee du Bandama" }, { id: "CI-WR", name: "Woroba" }, { id: "CI-YM", name: "Yamoussoukro", weight: 140 }, { id: "CI-ZZ", name: "Zanzan" }] },
    { code: "CL", name: "Chile", continent: "South America", populationM: 20, economy: 66, infrastructure: 72, tourism: 78, significance: 58, divisions: [{ id: "CL-RM", name: "Region Metropolitana", weight: 140 }, { id: "CL-VS", name: "Valparaiso" }, { id: "CL-AN", name: "Antofagasta" }, { id: "CL-AR", name: "Araucania" }, { id: "CL-BI", name: "Biobio" }, { id: "CL-CO", name: "Coquimbo" }, { id: "CL-LL", name: "Los Lagos" }, { id: "CL-MA", name: "Magallanes" }, { id: "CL-TA", name: "Tarapaca" }, { id: "CL-AT", name: "Atacama" }, { id: "CL-LI", name: "O'Higgins" }, { id: "CL-ML", name: "Maule" }, { id: "CL-NB", name: "Nuble" }, { id: "CL-LR", name: "Los Rios" }, { id: "CL-AI", name: "Aysen" }, { id: "CL-AP", name: "Arica y Parinacota" }] },
    { code: "CM", name: "Cameroon", continent: "Africa", populationM: 28, economy: 40, infrastructure: 35, tourism: 70, significance: 42, divisions: [{ id: "CM-CE", name: "Centre", weight: 140 }, { id: "CM-LT", name: "Littoral" }, { id: "CM-OU", name: "Ouest" }, { id: "CM-NO", name: "Nord" }, { id: "CM-EN", name: "Extreme-Nord" }, { id: "CM-AD", name: "Adamaoua" }, { id: "CM-SW", name: "Sud-Ouest" }, { id: "CM-NW", name: "Nord-Ouest" }, { id: "CM-SU", name: "Sud" }, { id: "CM-ES", name: "Est" }] },
    { code: "CN", name: "China", continent: "Asia", populationM: 1412, economy: 88, infrastructure: 80, tourism: 60, significance: 95, divisions: [{ id: "CN-BJ", name: "Beijing", weight: 180 }, { id: "CN-SH", name: "Shanghai", weight: 190 }, { id: "CN-GD", name: "Guangdong", weight: 170 }, { id: "CN-ZJ", name: "Zhejiang", weight: 150 }, { id: "CN-JS", name: "Jiangsu", weight: 140 }, { id: "CN-SC", name: "Sichuan", weight: 120 }, { id: "CN-HK", name: "Hong Kong", weight: 210 }, { id: "CN-MO", name: "Macau", weight: 190 }, { id: "CN-TW", name: "Taiwan", weight: 160 }, { id: "CN-FJ", name: "Fujian" }, { id: "CN-SD", name: "Shandong" }, { id: "CN-HN", name: "Henan" }, { id: "CN-HB", name: "Hubei" }, { id: "CN-HU", name: "Hunan" }, { id: "CN-HE", name: "Hebei" }, { id: "CN-SX", name: "Shanxi" }, { id: "CN-SN", name: "Shaanxi" }, { id: "CN-AH", name: "Anhui" }, { id: "CN-JX", name: "Jiangxi" }, { id: "CN-LN", name: "Liaoning" }, { id: "CN-JL", name: "Jilin" }, { id: "CN-HL", name: "Heilongjiang" }, { id: "CN-YN", name: "Yunnan" }, { id: "CN-GZ", name: "Guizhou" }, { id: "CN-GX", name: "Guangxi" }, { id: "CN-CQ", name: "Chongqing", weight: 135 }, { id: "CN-TJ", name: "Tianjin", weight: 130 }, { id: "CN-NM", name: "Inner Mongolia" }, { id: "CN-XJ", name: "Xinjiang" }, { id: "CN-GS", name: "Gansu" }, { id: "CN-QH", name: "Qinghai" }, { id: "CN-NX", name: "Ningxia" }, { id: "CN-XZ", name: "Tibet" }, { id: "CN-HI", name: "Hainan", weight: 130 }] },
    { code: "CO", name: "Colombia", continent: "South America", populationM: 52, economy: 52, infrastructure: 52, tourism: 72, significance: 55, divisions: [{ id: "CO-DC", name: "Bogota", weight: 150 }, { id: "CO-ANT", name: "Antioquia", weight: 120 }, { id: "CO-VAC", name: "Valle del Cauca" }, { id: "CO-ATL", name: "Atlantico" }, { id: "CO-BOL", name: "Bolivar" }, { id: "CO-SAN", name: "Santander" }, { id: "CO-CUN", name: "Cundinamarca" }, { id: "CO-MAG", name: "Magdalena" }, { id: "CO-COR", name: "Cordoba" }, { id: "CO-RIS", name: "Risaralda" }, { id: "CO-CAL", name: "Caldas" }, { id: "CO-QUI", name: "Quindio" }] },
    { code: "CR", name: "Costa Rica", continent: "North America", populationM: 5, economy: 65, infrastructure: 72, tourism: 95, significance: 55, divisions: [{ id: "CR-SJ", name: "San Jose", weight: 145 }, { id: "CR-A", name: "Alajuela" }, { id: "CR-C", name: "Cartago" }, { id: "CR-H", name: "Heredia" }, { id: "CR-G", name: "Guanacaste", weight: 155 }, { id: "CR-P", name: "Puntarenas", weight: 150 }, { id: "CR-L", name: "Limon" }] },
    { code: "CY", name: "Cyprus", continent: "Europe", populationM: 1, economy: 62, infrastructure: 72, tourism: 92, significance: 48, divisions: [{ id: "CY-01", name: "Nicosia" }, { id: "CY-02", name: "Limassol", weight: 140 }, { id: "CY-03", name: "Larnaca", weight: 135 }, { id: "CY-04", name: "Famagusta" }, { id: "CY-05", name: "Paphos", weight: 135 }, { id: "CY-06", name: "Kyrenia" }] },
    { code: "CZ", name: "Czechia", continent: "Europe", populationM: 11, economy: 72, infrastructure: 78, tourism: 82, significance: 60, divisions: [{ id: "CZ-10", name: "Prague", weight: 170 }, { id: "CZ-64", name: "South Moravian" }, { id: "CZ-31", name: "South Bohemian", weight: 135 }, { id: "CZ-51", name: "Liberec" }, { id: "CZ-52", name: "Hradec Kralove" }, { id: "CZ-53", name: "Pardubice" }, { id: "CZ-41", name: "Karlovy Vary", weight: 140 }, { id: "CZ-42", name: "Usti nad Labem" }, { id: "CZ-32", name: "Plzen" }, { id: "CZ-71", name: "Olomouc" }, { id: "CZ-72", name: "Zlin" }, { id: "CZ-80", name: "Moravian-Silesian" }, { id: "CZ-20", name: "Central Bohemian" }, { id: "CZ-63", name: "Vysocina" }] },
    { code: "DE", name: "Germany", continent: "Europe", populationM: 84, economy: 95, infrastructure: 95, tourism: 80, significance: 92, divisions: [{ id: "DE-BE", name: "Berlin", weight: 175 }, { id: "DE-BY", name: "Bavaria", weight: 150 }, { id: "DE-BW", name: "Baden-Wuerttemberg", weight: 135 }, { id: "DE-NW", name: "North Rhine-Westphalia", weight: 130 }, { id: "DE-HE", name: "Hesse", weight: 135 }, { id: "DE-HH", name: "Hamburg", weight: 150 }, { id: "DE-NI", name: "Lower Saxony" }, { id: "DE-SN", name: "Saxony" }, { id: "DE-RP", name: "Rhineland-Palatinate" }, { id: "DE-SH", name: "Schleswig-Holstein" }, { id: "DE-BB", name: "Brandenburg" }, { id: "DE-TH", name: "Thuringia" }, { id: "DE-ST", name: "Saxony-Anhalt" }, { id: "DE-MV", name: "Mecklenburg-Vorpommern" }, { id: "DE-SL", name: "Saarland" }, { id: "DE-HB", name: "Bremen" }] },
    { code: "DK", name: "Denmark", continent: "Europe", populationM: 6, economy: 85, infrastructure: 94, tourism: 80, significance: 68, divisions: [{ id: "DK-84", name: "Capital Region", weight: 150 }, { id: "DK-82", name: "Central Jutland" }, { id: "DK-83", name: "Southern Denmark" }, { id: "DK-81", name: "North Jutland" }, { id: "DK-85", name: "Zealand" }] },
    { code: "DO", name: "Dominican Republic", continent: "North America", populationM: 11, economy: 52, infrastructure: 58, tourism: 88, significance: 50, divisions: [{ id: "DO-01", name: "Distrito Nacional", weight: 140 }, { id: "DO-32", name: "Santo Domingo" }, { id: "DO-02", name: "Azua" }, { id: "DO-03", name: "Bahoruco" }, { id: "DO-04", name: "Barahona" }, { id: "DO-05", name: "Dajabon" }, { id: "DO-06", name: "Duarte" }, { id: "DO-07", name: "Elias Pina" }, { id: "DO-08", name: "El Seibo" }, { id: "DO-09", name: "Espaillat" }, { id: "DO-10", name: "Independencia" }, { id: "DO-11", name: "La Altagracia", weight: 150 }, { id: "DO-12", name: "La Romana", weight: 145 }, { id: "DO-13", name: "La Vega" }, { id: "DO-14", name: "Maria Trinidad Sanchez" }, { id: "DO-15", name: "Monte Cristi" }, { id: "DO-16", name: "Pedernales" }, { id: "DO-17", name: "Peravia" }, { id: "DO-18", name: "Puerto Plata", weight: 145 }, { id: "DO-19", name: "Hermanas Mirabal" }, { id: "DO-20", name: "Samana", weight: 140 }, { id: "DO-21", name: "San Cristobal" }, { id: "DO-22", name: "San Juan" }, { id: "DO-23", name: "San Pedro de Macoris" }, { id: "DO-24", name: "Sanchez Ramirez" }, { id: "DO-25", name: "Santiago" }, { id: "DO-26", name: "Santiago Rodriguez" }, { id: "DO-27", name: "Valverde" }, { id: "DO-28", name: "Monsenor Nouel" }, { id: "DO-29", name: "Monte Plata" }, { id: "DO-30", name: "Hato Mayor" }, { id: "DO-31", name: "San Jose de Ocoa" }, { id: "DO-33", name: "Santo Domingo Este" }, { id: "DO-34", name: "Santo Domingo Norte" }, { id: "DO-35", name: "Santo Domingo Oeste" }, { id: "DO-36", name: "Boca Chica" }] },
    { code: "DZ", name: "Algeria", continent: "Africa", populationM: 46, economy: 42, infrastructure: 45, tourism: 65, significance: 45, divisions: [{ id: "DZ-16", name: "Algiers", weight: 145 }, { id: "DZ-31", name: "Oran" }, { id: "DZ-25", name: "Constantine" }, { id: "DZ-06", name: "Bejaia" }, { id: "DZ-19", name: "Setif" }, { id: "DZ-09", name: "Blida" }, { id: "DZ-35", name: "Boumerdes" }, { id: "DZ-23", name: "Annaba" }, { id: "DZ-30", name: "Ouargla" }, { id: "DZ-11", name: "Tamanrasset" }, { id: "DZ-01", name: "Adrar" }, { id: "DZ-47", name: "Ghardaia" }] },
    { code: "EC", name: "Ecuador", continent: "South America", populationM: 18, economy: 45, infrastructure: 50, tourism: 85, significance: 48, divisions: [{ id: "EC-P", name: "Pichincha", weight: 145 }, { id: "EC-G", name: "Guayas" }, { id: "EC-A", name: "Azuay" }, { id: "EC-M", name: "Manabi" }, { id: "EC-L", name: "Loja" }, { id: "EC-T", name: "Tungurahua" }, { id: "EC-I", name: "Imbabura" }, { id: "EC-R", name: "Los Rios" }, { id: "EC-SD", name: "Santo Domingo" }, { id: "EC-E", name: "Esmeraldas" }, { id: "EC-O", name: "El Oro" }, { id: "EC-X", name: "Cotopaxi" }, { id: "EC-W", name: "Galapagos", weight: 160 }] },
    { code: "EE", name: "Estonia", continent: "Europe", populationM: 1, economy: 72, infrastructure: 82, tourism: 72, significance: 52, divisions: [{ id: "EE-37", name: "Harju", weight: 135 }, { id: "EE-49", name: "Ida-Viru" }, { id: "EE-51", name: "Jarva" }, { id: "EE-57", name: "Laane" }, { id: "EE-59", name: "Laane-Viru" }, { id: "EE-65", name: "Polva" }, { id: "EE-67", name: "Parnu" }, { id: "EE-70", name: "Rapla" }, { id: "EE-74", name: "Saare" }, { id: "EE-78", name: "Tartu", weight: 135 }, { id: "EE-82", name: "Valga" }, { id: "EE-84", name: "Viljandi" }, { id: "EE-86", name: "Voru" }] },
    { code: "EG", name: "Egypt", continent: "Africa", populationM: 113, economy: 50, infrastructure: 55, tourism: 92, significance: 60, divisions: [{ id: "EG-C", name: "Cairo", weight: 170 }, { id: "EG-ALX", name: "Alexandria", weight: 140 }, { id: "EG-GZ", name: "Giza" }, { id: "EG-LX", name: "Luxor", weight: 150 }, { id: "EG-ASN", name: "Aswan", weight: 145 }, { id: "EG-BA", name: "Red Sea", weight: 150 }, { id: "EG-JS", name: "South Sinai", weight: 155 }, { id: "EG-SIN", name: "North Sinai" }, { id: "EG-MT", name: "Matrouh" }, { id: "EG-IS", name: "Ismailia" }, { id: "EG-PTS", name: "Port Said" }, { id: "EG-SUZ", name: "Suez" }, { id: "EG-DK", name: "Dakahlia" }, { id: "EG-SHR", name: "Sharqia" }, { id: "EG-GH", name: "Gharbia" }, { id: "EG-MNF", name: "Monufia" }, { id: "EG-BH", name: "Beheira" }, { id: "EG-KFS", name: "Kafr El Sheikh" }, { id: "EG-DT", name: "Damietta" }, { id: "EG-FYM", name: "Faiyum" }, { id: "EG-BNS", name: "Beni Suef" }, { id: "EG-MN", name: "Minya" }, { id: "EG-AST", name: "Asyut" }, { id: "EG-SHG", name: "Sohag" }, { id: "EG-KN", name: "Qena" }, { id: "EG-WAD", name: "New Valley" }] },
    { code: "ES", name: "Spain", continent: "Europe", populationM: 48, economy: 78, infrastructure: 85, tourism: 98, significance: 85, divisions: [{ id: "ES-MD", name: "Madrid", weight: 175 }, { id: "ES-CT", name: "Catalonia", weight: 175 }, { id: "ES-AN", name: "Andalusia", weight: 150 }, { id: "ES-VC", name: "Valencian Community", weight: 155 }, { id: "ES-IB", name: "Balearic Islands", weight: 175 }, { id: "ES-CN", name: "Canary Islands", weight: 160 }, { id: "ES-GA", name: "Galicia" }, { id: "ES-PV", name: "Basque Country" }, { id: "ES-CL", name: "Castile and Leon" }, { id: "ES-CM", name: "Castile-La Mancha" }, { id: "ES-AR", name: "Aragon" }, { id: "ES-AS", name: "Asturias" }, { id: "ES-NC", name: "Navarre" }, { id: "ES-MC", name: "Murcia" }, { id: "ES-EX", name: "Extremadura" }, { id: "ES-CB", name: "Cantabria" }, { id: "ES-RI", name: "La Rioja" }] },
    { code: "ET", name: "Ethiopia", continent: "Africa", populationM: 126, economy: 32, infrastructure: 25, tourism: 55, significance: 42, divisions: [{ id: "ET-AA", name: "Addis Ababa", weight: 145 }, { id: "ET-OR", name: "Oromia" }, { id: "ET-AM", name: "Amhara" }, { id: "ET-TI", name: "Tigray" }, { id: "ET-SN", name: "SNNPR" }, { id: "ET-SO", name: "Somali" }, { id: "ET-AF", name: "Afar" }, { id: "ET-BE", name: "Benishangul-Gumuz" }, { id: "ET-GA", name: "Gambela" }, { id: "ET-HA", name: "Harari" }, { id: "ET-DD", name: "Dire Dawa" }] },
    { code: "FI", name: "Finland", continent: "Europe", populationM: 6, economy: 82, infrastructure: 92, tourism: 72, significance: 62, divisions: [{ id: "FI-18", name: "Uusimaa", weight: 150 }, { id: "FI-17", name: "Satakunta" }, { id: "FI-19", name: "Varsinais-Suomi" }, { id: "FI-13", name: "Lappi", weight: 140 }, { id: "FI-11", name: "Pirkanmaa" }, { id: "FI-09", name: "Kymenlaakso" }, { id: "FI-07", name: "Keski-Suomi" }] },
    { code: "FR", name: "France", continent: "Europe", populationM: 68, economy: 92, infrastructure: 95, tourism: 95, significance: 92, divisions: [{ id: "FR-IDF", name: "Ile-de-France", weight: 200 }, { id: "FR-ARA", name: "Auvergne-Rhone-Alpes", weight: 140 }, { id: "FR-PAC", name: "Provence-Alpes-Cote d'Azur", weight: 165 }, { id: "FR-NAQ", name: "Nouvelle-Aquitaine", weight: 135 }, { id: "FR-OCC", name: "Occitanie", weight: 135 }, { id: "FR-HDF", name: "Hauts-de-France" }, { id: "FR-GES", name: "Grand Est" }, { id: "FR-PDL", name: "Pays de la Loire" }, { id: "FR-BRE", name: "Bretagne" }, { id: "FR-NOR", name: "Normandie" }, { id: "FR-CVL", name: "Centre-Val de Loire" }, { id: "FR-BFC", name: "Bourgogne-Franche-Comte" }, { id: "FR-COR", name: "Corse", weight: 150 }] },
    { code: "GE", name: "Georgia", continent: "Asia", populationM: 4, economy: 48, infrastructure: 55, tourism: 80, significance: 42, divisions: [{ id: "GE-TB", name: "Tbilisi", weight: 140 }, { id: "GE-AB", name: "Abkhazia" }, { id: "GE-AJ", name: "Adjara", weight: 135 }, { id: "GE-GU", name: "Guria" }, { id: "GE-IM", name: "Imereti" }, { id: "GE-KA", name: "Kakheti", weight: 130 }, { id: "GE-KV", name: "Kvemo Kartli" }, { id: "GE-MM", name: "Mtskheta-Mtianeti" }, { id: "GE-RL", name: "Racha-Lechkhumi" }, { id: "GE-SJ", name: "Samtskhe-Javakheti" }, { id: "GE-SK", name: "Shida Kartli" }, { id: "GE-SZ", name: "Samegrelo-Zemo Svaneti" }] },
    { code: "GH", name: "Ghana", continent: "Africa", populationM: 34, economy: 42, infrastructure: 38, tourism: 72, significance: 45, divisions: [{ id: "GH-AA", name: "Greater Accra", weight: 140 }, { id: "GH-AH", name: "Ashanti" }, { id: "GH-WP", name: "Western" }, { id: "GH-CP", name: "Central" }, { id: "GH-EP", name: "Eastern" }, { id: "GH-NP", name: "Northern" }, { id: "GH-TV", name: "Volta" }, { id: "GH-UE", name: "Upper East" }, { id: "GH-UW", name: "Upper West" }, { id: "GH-BO", name: "Bono" }] },
    { code: "GR", name: "Greece", continent: "Europe", populationM: 10, economy: 60, infrastructure: 66, tourism: 95, significance: 58, divisions: [{ id: "GR-I", name: "Attica", weight: 160 }, { id: "GR-B", name: "Central Macedonia", weight: 135 }, { id: "GR-M", name: "Crete", weight: 150 }, { id: "GR-L", name: "South Aegean", weight: 165 }, { id: "GR-J", name: "Ionian Islands", weight: 150 }, { id: "GR-A", name: "East Macedonia and Thrace" }, { id: "GR-D", name: "Epirus" }, { id: "GR-E", name: "Thessaly" }, { id: "GR-F", name: "Ionian" }, { id: "GR-G", name: "West Greece" }, { id: "GR-H", name: "Central Greece" }, { id: "GR-K", name: "North Aegean" }, { id: "GR-L2", name: "Peloponnese" }] },
    { code: "GT", name: "Guatemala", continent: "North America", populationM: 18, economy: 45, infrastructure: 42, tourism: 82, significance: 48, divisions: [{ id: "GT-GU", name: "Guatemala", weight: 145 }, { id: "GT-AV", name: "Alta Verapaz" }, { id: "GT-BV", name: "Baja Verapaz" }, { id: "GT-CM", name: "Chimaltenango" }, { id: "GT-CQ", name: "Chiquimula" }, { id: "GT-ES", name: "Escuintla" }, { id: "GT-PE", name: "Peten", weight: 140 }, { id: "GT-QZ", name: "Quetzaltenango" }, { id: "GT-SA", name: "Sacatepequez", weight: 150 }, { id: "GT-SO", name: "Solola", weight: 145 }, { id: "GT-ZA", name: "Zacapa" }] },
    { code: "GY", name: "Guyana", continent: "South America", populationM: 1, economy: 42, infrastructure: 45, tourism: 70, significance: 38, divisions: [{ id: "GY-DE", name: "Demerara-Mahaica", weight: 140 }, { id: "GY-ES", name: "Essequibo Islands-West Demerara" }, { id: "GY-MA", name: "Mahaica-Berbice" }, { id: "GY-EB", name: "East Berbice-Corentyne" }, { id: "GY-Dem", name: "Demerara" }, { id: "GY-PM", name: "Pomeroon-Supenaam" }, { id: "GY-CU", name: "Cuyuni-Mazaruni" }, { id: "GY-UT", name: "Upper Takutu-Upper Essequibo" }, { id: "GY-PT", name: "Potaro-Siparuni" }, { id: "GY-BA", name: "Barima-Waini" }] },
    { code: "HN", name: "Honduras", continent: "North America", populationM: 10, economy: 38, infrastructure: 38, tourism: 78, significance: 45, divisions: [{ id: "HN-FM", name: "Francisco Morazan", weight: 140 }, { id: "HN-CR", name: "Cortes" }, { id: "HN-AT", name: "Atlantida", weight: 140 }, { id: "HN-IB", name: "Islas de la Bahia", weight: 150 }, { id: "HN-CL", name: "Colon" }, { id: "HN-CM", name: "Comayagua" }, { id: "HN-CP", name: "Copan" }, { id: "HN-CH", name: "Choluteca" }] },
    { code: "HR", name: "Croatia", continent: "Europe", populationM: 4, economy: 58, infrastructure: 68, tourism: 90, significance: 50, divisions: [{ id: "HR-21", name: "Zagreb", weight: 145 }, { id: "HR-17", name: "Split-Dalmatia", weight: 140 }, { id: "HR-08", name: "Primorje-Gorski Kotar", weight: 135 }, { id: "HR-19", name: "Dubrovnik-Neretva", weight: 150 }, { id: "HR-13", name: "Zadar", weight: 135 }, { id: "HR-18", name: "Sibenik-Knin", weight: 130 }, { id: "HR-07", name: "Bjelovar-Bilogora" }, { id: "HR-01", name: "Zagreb County" }, { id: "HR-02", name: "Krapina-Zagorje" }, { id: "HR-03", name: "Sisak-Moslavina" }, { id: "HR-04", name: "Karlovac" }, { id: "HR-05", name: "Varazdin" }, { id: "HR-06", name: "Koprivnica-Krizevci" }, { id: "HR-09", name: "Lika-Senj" }, { id: "HR-10", name: "Virovitica-Podravina" }, { id: "HR-11", name: "Pozega-Slavonia" }, { id: "HR-12", name: "Brod-Posavina" }, { id: "HR-14", name: "Osijek-Baranja" }, { id: "HR-15", name: "Sibenik" }, { id: "HR-16", name: "Vukovar-Srijem" }, { id: "HR-20", name: "Medimurje" }] },
    { code: "HU", name: "Hungary", continent: "Europe", populationM: 10, economy: 62, infrastructure: 72, tourism: 82, significance: 58, divisions: [{ id: "HU-BU", name: "Budapest", weight: 165 }, { id: "HU-PE", name: "Pest" }, { id: "HU-GY", name: "Gyor-Moson-Sopron" }, { id: "HU-BA", name: "Baranya" }, { id: "HU-SZ", name: "Szabolcs-Szatmar-Bereg" }, { id: "HU-HB", name: "Hajdu-Bihar" }, { id: "HU-CS", name: "Csongrad-Csanad" }, { id: "HU-VE", name: "Veszprem" }, { id: "HU-ZA", name: "Zala" }, { id: "HU-SO", name: "Somogy" }, { id: "HU-BK", name: "Bacs-Kiskun" }, { id: "HU-HE", name: "Heves" }, { id: "HU-JN", name: "Jasz-Nagykun-Szolnok" }, { id: "HU-TO", name: "Tolna" }, { id: "HU-VA", name: "Vas" }, { id: "HU-NO", name: "Nograd" }, { id: "HU-BE", name: "Bekes" }, { id: "HU-FE", name: "Fejer" }, { id: "HU-KE", name: "Komarom-Esztergom" }] },
    { code: "ID", name: "Indonesia", continent: "Asia", populationM: 278, economy: 58, infrastructure: 45, tourism: 85, significance: 62, divisions: [{ id: "ID-JK", name: "Jakarta", weight: 160 }, { id: "ID-BA", name: "Bali", weight: 190 }, { id: "ID-JB", name: "West Java", weight: 120 }, { id: "ID-JT", name: "Central Java" }, { id: "ID-JI", name: "East Java" }, { id: "ID-SU", name: "North Sumatra" }, { id: "ID-SN", name: "South Sulawesi" }, { id: "ID-SG", name: "Southeast Sulawesi" }, { id: "ID-AC", name: "Aceh" }, { id: "ID-YO", name: "Yogyakarta", weight: 140 }, { id: "ID-BT", name: "Banten" }, { id: "ID-KI", name: "East Kalimantan" }, { id: "ID-PA", name: "Papua" }, { id: "ID-LA", name: "Lampung" }, { id: "ID-SS", name: "South Sumatra" }, { id: "ID-RI", name: "Riau" }, { id: "ID-KB", name: "West Kalimantan" }, { id: "ID-KS", name: "South Kalimantan" }, { id: "ID-DI", name: "South Sulawesi" }, { id: "ID-NB", name: "West Nusa Tenggara" }, { id: "ID-NT", name: "East Nusa Tenggara" }] },
    { code: "IE", name: "Ireland", continent: "Europe", populationM: 5, economy: 80, infrastructure: 85, tourism: 88, significance: 62, divisions: [{ id: "IE-L", name: "Leinster", weight: 140 }, { id: "IE-M", name: "Munster" }, { id: "IE-C", name: "Connacht" }, { id: "IE-U", name: "Ulster" }] },
    { code: "IL", name: "Israel", continent: "Asia", populationM: 10, economy: 92, infrastructure: 95, tourism: 88, significance: 82, divisions: [{ id: "IL-TA", name: "Tel Aviv", weight: 180 }, { id: "IL-JM", name: "Jerusalem", weight: 180 }, { id: "IL-HA", name: "Haifa", weight: 150 }, { id: "IL-D", name: "Southern" }, { id: "IL-M", name: "Central" }, { id: "IL-Z", name: "Northern" }, { id: "IL-RL", name: "Rehovot" }] },
    { code: "IN", name: "India", continent: "Asia", populationM: 1428, economy: 72, infrastructure: 45, tourism: 80, significance: 85, divisions: [{ id: "IN-MH", name: "Maharashtra", weight: 150 }, { id: "IN-DL", name: "Delhi", weight: 170 }, { id: "IN-KA", name: "Karnataka", weight: 130 }, { id: "IN-TN", name: "Tamil Nadu", weight: 120 }, { id: "IN-UP", name: "Uttar Pradesh" }, { id: "IN-GJ", name: "Gujarat" }, { id: "IN-WB", name: "West Bengal" }, { id: "IN-RJ", name: "Rajasthan" }, { id: "IN-TG", name: "Telangana" }, { id: "IN-KL", name: "Kerala", weight: 120 }, { id: "IN-HR", name: "Haryana" }, { id: "IN-PB", name: "Punjab" }, { id: "IN-MP", name: "Madhya Pradesh" }, { id: "IN-BR", name: "Bihar" }, { id: "IN-OD", name: "Odisha" }, { id: "IN-AP", name: "Andhra Pradesh" }, { id: "IN-AS", name: "Assam" }, { id: "IN-JH", name: "Jharkhand" }, { id: "IN-CT", name: "Chhattisgarh" }, { id: "IN-UT", name: "Uttarakhand" }, { id: "IN-HP", name: "Himachal Pradesh" }, { id: "IN-GA", name: "Goa", weight: 130 }, { id: "IN-JK", name: "Jammu and Kashmir" }, { id: "IN-TR", name: "Tripura" }, { id: "IN-ML", name: "Meghalaya" }, { id: "IN-MN", name: "Manipur" }, { id: "IN-NL", name: "Nagaland" }, { id: "IN-AR", name: "Arunachal Pradesh" }, { id: "IN-MZ", name: "Mizoram" }, { id: "IN-SK", name: "Sikkim" }, { id: "IN-CH", name: "Chandigarh" }, { id: "IN-PY", name: "Puducherry" }, { id: "IN-AN", name: "Andaman and Nicobar Islands" }, { id: "IN-LA", name: "Ladakh" }, { id: "IN-DN", name: "Dadra and Nagar Haveli" }] },
    { code: "IQ", name: "Iraq", continent: "Asia", populationM: 45, economy: 38, infrastructure: 35, tourism: 55, significance: 50, divisions: [{ id: "IQ-BG", name: "Baghdad", weight: 150 }, { id: "IQ-BA", name: "Basra" }, { id: "IQ-NA", name: "Najaf", weight: 140 }, { id: "IQ-KA", name: "Karbala", weight: 140 }, { id: "IQ-AR", name: "Erbil" }, { id: "IQ-SU", name: "Sulaymaniyah" }, { id: "IQ-DA", name: "Duhok" }, { id: "IQ-NI", name: "Nineveh" }, { id: "IQ-AN", name: "Anbar" }, { id: "IQ-DI", name: "Diyala" }, { id: "IQ-KI", name: "Kirkuk" }, { id: "IQ-WA", name: "Wasit" }, { id: "IQ-MA", name: "Maysan" }, { id: "IQ-DQ", name: "Dhi Qar" }, { id: "IQ-MU", name: "Muthanna" }, { id: "IQ-QA", name: "Qadisiyyah" }, { id: "IQ-BB", name: "Babil" }, { id: "IQ-SD", name: "Saladin" }] },
    { code: "IR", name: "Iran", continent: "Asia", populationM: 89, economy: 48, infrastructure: 50, tourism: 60, significance: 58, divisions: [{ id: "IR-07", name: "Tehran", weight: 160 }, { id: "IR-04", name: "East Azerbaijan" }, { id: "IR-08", name: "Isfahan", weight: 140 }, { id: "IR-21", name: "Razavi Khorasan", weight: 140 }, { id: "IR-23", name: "Fars", weight: 145 }, { id: "IR-05", name: "West Azerbaijan" }, { id: "IR-06", name: "Khuzestan" }, { id: "IR-03", name: "Ardabil" }, { id: "IR-09", name: "Kerman" }, { id: "IR-10", name: "Kermanshah" }, { id: "IR-11", name: "Golestan" }, { id: "IR-12", name: "Gilan" }, { id: "IR-13", name: "Lorestan" }, { id: "IR-14", name: "Mazandaran" }, { id: "IR-15", name: "Markazi" }, { id: "IR-16", name: "Hormozgan" }, { id: "IR-17", name: "Qazvin" }, { id: "IR-18", name: "Qom" }, { id: "IR-19", name: "Zanjan" }, { id: "IR-20", name: "Semnan" }, { id: "IR-22", name: "Qeshm" }] },
    { code: "IS", name: "Iceland", continent: "Europe", populationM: 1, economy: 80, infrastructure: 85, tourism: 95, significance: 55, divisions: [{ id: "IS-1", name: "Capital Region", weight: 150 }, { id: "IS-2", name: "Southern Peninsula" }, { id: "IS-3", name: "Western Region" }, { id: "IS-4", name: "Westfjords", weight: 140 }, { id: "IS-5", name: "Northwest" }, { id: "IS-6", name: "Northeast", weight: 140 }, { id: "IS-7", name: "Eastern" }, { id: "IS-8", name: "Southern" }] },
    { code: "IT", name: "Italy", continent: "Europe", populationM: 59, economy: 82, infrastructure: 85, tourism: 98, significance: 88, divisions: [{ id: "IT-62", name: "Lazio", weight: 170 }, { id: "IT-25", name: "Lombardy", weight: 150 }, { id: "IT-34", name: "Veneto", weight: 160 }, { id: "IT-52", name: "Tuscany", weight: 170 }, { id: "IT-72", name: "Campania", weight: 140 }, { id: "IT-32", name: "Trentino-Alto Adige" }, { id: "IT-21", name: "Piedmont" }, { id: "IT-42", name: "Liguria", weight: 150 }, { id: "IT-36", name: "Friuli-Venezia Giulia" }, { id: "IT-55", name: "Umbria", weight: 140 }, { id: "IT-45", name: "Emilia-Romagna", weight: 140 }, { id: "IT-82", name: "Sicily", weight: 140 }, { id: "IT-75", name: "Apulia" }, { id: "IT-65", name: "Abruzzo" }, { id: "IT-77", name: "Basilicata" }, { id: "IT-78", name: "Calabria" }, { id: "IT-57", name: "Marche" }, { id: "IT-67", name: "Molise" }, { id: "IT-23", name: "Aosta Valley" }, { id: "IT-88", name: "Sardinia", weight: 145 }] },
    { code: "JM", name: "Jamaica", continent: "North America", populationM: 3, economy: 48, infrastructure: 55, tourism: 88, significance: 48, divisions: [{ id: "JM-01", name: "Kingston", weight: 140 }, { id: "JM-02", name: "Saint Andrew" }, { id: "JM-03", name: "Saint Thomas" }, { id: "JM-04", name: "Portland" }, { id: "JM-05", name: "Saint Mary" }, { id: "JM-06", name: "Saint Ann", weight: 140 }, { id: "JM-07", name: "Trelawny" }, { id: "JM-08", name: "Saint James", weight: 140 }, { id: "JM-09", name: "Hanover" }, { id: "JM-10", name: "Westmoreland" }, { id: "JM-11", name: "Saint Elizabeth" }, { id: "JM-12", name: "Manchester" }, { id: "JM-13", name: "Clarendon" }, { id: "JM-14", name: "Saint Catherine" }] },
    { code: "JO", name: "Jordan", continent: "Asia", populationM: 11, economy: 50, infrastructure: 58, tourism: 80, significance: 48, divisions: [{ id: "JO-AM", name: "Amman", weight: 145 }, { id: "JO-AQ", name: "Aqaba", weight: 145 }, { id: "JO-IR", name: "Irbid" }, { id: "JO-ZA", name: "Zarqa" }, { id: "JO-BA", name: "Balqa" }, { id: "JO-MA", name: "Mafraq" }, { id: "JO-KA", name: "Karak" }, { id: "JO-MN", name: "Ma'an" }, { id: "JO-AT", name: "Tafilah" }, { id: "JO-AZ", name: "Zarqa" }] },
    { code: "JP", name: "Japan", continent: "Asia", populationM: 124, economy: 88, infrastructure: 95, tourism: 85, significance: 88, divisions: [{ id: "JP-13", name: "Tokyo", weight: 210 }, { id: "JP-27", name: "Osaka", weight: 160 }, { id: "JP-23", name: "Aichi" }, { id: "JP-14", name: "Kanagawa" }, { id: "JP-34", name: "Hiroshima" }, { id: "JP-01", name: "Hokkaido", weight: 140 }, { id: "JP-26", name: "Kyoto", weight: 190 }, { id: "JP-40", name: "Fukuoka" }, { id: "JP-28", name: "Hyogo" }, { id: "JP-22", name: "Shizuoka" }, { id: "JP-11", name: "Saitama" }, { id: "JP-12", name: "Chiba" }, { id: "JP-15", name: "Niigata" }, { id: "JP-20", name: "Nagano" }, { id: "JP-19", name: "Yamanashi" }, { id: "JP-25", name: "Shiga" }, { id: "JP-29", name: "Nara" }, { id: "JP-33", name: "Okayama" }, { id: "JP-37", name: "Kagawa" }, { id: "JP-43", name: "Kumamoto" }, { id: "JP-47", name: "Okinawa", weight: 150 }, { id: "JP-04", name: "Miyagi" }, { id: "JP-17", name: "Ishikawa" }, { id: "JP-21", name: "Gifu" }, { id: "JP-24", name: "Mie" }, { id: "JP-30", name: "Wakayama" }, { id: "JP-31", name: "Tottori" }, { id: "JP-32", name: "Shimane" }, { id: "JP-35", name: "Yamaguchi" }, { id: "JP-36", name: "Tokushima" }, { id: "JP-38", name: "Ehime" }, { id: "JP-39", name: "Kochi" }, { id: "JP-41", name: "Saga" }, { id: "JP-42", name: "Nagasaki" }, { id: "JP-44", name: "Oita" }, { id: "JP-45", name: "Miyazaki" }, { id: "JP-46", name: "Kagoshima" }, { id: "JP-02", name: "Aomori" }, { id: "JP-03", name: "Iwate" }, { id: "JP-05", name: "Akita" }, { id: "JP-06", name: "Yamagata" }, { id: "JP-07", name: "Fukushima" }, { id: "JP-08", name: "Ibaraki" }, { id: "JP-09", name: "Tochigi" }, { id: "JP-10", name: "Gunma" }, { id: "JP-16", name: "Toyama" }, { id: "JP-18", name: "Fukui" }] },
    { code: "KE", name: "Kenya", continent: "Africa", populationM: 55, economy: 45, infrastructure: 42, tourism: 88, significance: 55, divisions: [{ id: "KE-30", name: "Nairobi", weight: 150 }, { id: "KE-01", name: "Mombasa", weight: 140 }, { id: "KE-19", name: "Nakuru" }, { id: "KE-32", name: "Kisumu" }, { id: "KE-27", name: "Narok" }, { id: "KE-16", name: "Kajiado" }, { id: "KE-28", name: "Kiambu" }, { id: "KE-36", name: "Nairobi County" }, { id: "KE-41", name: "Turkana" }] },
    { code: "KH", name: "Cambodia", continent: "Asia", populationM: 17, economy: 38, infrastructure: 32, tourism: 85, significance: 45, divisions: [{ id: "KH-PNH", name: "Phnom Penh", weight: 150 }, { id: "KH-SR", name: "Siem Reap", weight: 165 }, { id: "KH-BTB", name: "Battambang" }, { id: "KH-KPS", name: "Kampong Speu" }, { id: "KH-1", name: "Banteay Meanchey" }, { id: "KH-2", name: "Kampong Cham" }, { id: "KH-4", name: "Kampong Chhnang" }, { id: "KH-5", name: "Kampong Thom" }, { id: "KH-6", name: "Kampot" }, { id: "KH-7", name: "Kandal" }, { id: "KH-8", name: "Koh Kong" }, { id: "KH-9", name: "Kratie" }, { id: "KH-10", name: "Mondulkiri" }, { id: "KH-11", name: "Preah Vihear" }, { id: "KH-12", name: "Prey Veng" }, { id: "KH-13", name: "Pursat" }, { id: "KH-14", name: "Preah Sihanouk", weight: 140 }, { id: "KH-15", name: "Stung Treng" }, { id: "KH-16", name: "Svay Rieng" }, { id: "KH-17", name: "Takeo" }, { id: "KH-18", name: "Oddar Meanchey" }, { id: "KH-19", name: "Kep" }, { id: "KH-20", name: "Pailin" }, { id: "KH-21", name: "Tboung Khmum" }] },
    { code: "KR", name: "South Korea", continent: "Asia", populationM: 52, economy: 85, infrastructure: 95, tourism: 70, significance: 80, divisions: [{ id: "KR-11", name: "Seoul", weight: 200 }, { id: "KR-26", name: "Busan", weight: 140 }, { id: "KR-28", name: "Incheon", weight: 140 }, { id: "KR-27", name: "Daegu" }, { id: "KR-30", name: "Daejeon" }, { id: "KR-29", name: "Gwangju" }, { id: "KR-41", name: "Gyeonggi" }, { id: "KR-31", name: "Ulsan" }, { id: "KR-49", name: "Jeju", weight: 150 }, { id: "KR-42", name: "Gangwon" }, { id: "KR-43", name: "Chungcheongbuk" }, { id: "KR-44", name: "Chungcheongnam" }, { id: "KR-45", name: "Jeollabuk" }, { id: "KR-46", name: "Jeollanam" }, { id: "KR-47", name: "Gyeongsangbuk" }, { id: "KR-48", name: "Gyeongsangnam" }, { id: "KR-50", name: "Sejong" }] },
    { code: "KW", name: "Kuwait", continent: "Asia", populationM: 4, economy: 80, infrastructure: 88, tourism: 70, significance: 68, divisions: [{ id: "KW-KU", name: "Al Asimah", weight: 150 }, { id: "KW-AH", name: "Al Ahmadi" }, { id: "KW-FA", name: "Al Farwaniyah" }, { id: "KW-HA", name: "Hawalli" }, { id: "KW-JA", name: "Al Jahra" }, { id: "KW-MU", name: "Mubarak Al-Kabeer" }] },
    { code: "KZ", name: "Kazakhstan", continent: "Asia", populationM: 20, economy: 58, infrastructure: 62, tourism: 55, significance: 52, divisions: [{ id: "KZ-AST", name: "Astana", weight: 145 }, { id: "KZ-ALA", name: "Almaty", weight: 150 }, { id: "KZ-SHY", name: "Shymkent" }, { id: "KZ-KAR", name: "Karaganda" }, { id: "KZ-MAN", name: "Mangystau" }, { id: "KZ-ATY", name: "Atyrau" }, { id: "KZ-PAV", name: "Pavlodar" }, { id: "KZ-VOS", name: "East Kazakhstan" }, { id: "KZ-ZHA", name: "Zhambyl" }, { id: "KZ-TUR", name: "Turkistan" }] },
    { code: "LA", name: "Laos", continent: "Asia", populationM: 8, economy: 32, infrastructure: 28, tourism: 70, significance: 38, divisions: [{ id: "LA-VT", name: "Vientiane", weight: 140 }, { id: "LA-LP", name: "Luang Prabang", weight: 150 }, { id: "LA-CH", name: "Champasak" }, { id: "LA-OU", name: "Oudomxay" }, { id: "LA-BK", name: "Bokeo" }, { id: "LA-KH", name: "Khammouane" }, { id: "LA-SV", name: "Savannakhet" }] },
    { code: "LB", name: "Lebanon", continent: "Asia", populationM: 5, economy: 42, infrastructure: 50, tourism: 78, significance: 45, divisions: [{ id: "LB-BA", name: "Beirut", weight: 145 }, { id: "LB-JL", name: "Mount Lebanon" }, { id: "LB-AS", name: "North" }, { id: "LB-BI", name: "Bekaa" }, { id: "LB-NA", name: "Nabatieh" }, { id: "LB-SK", name: "South" }] },
    { code: "LK", name: "Sri Lanka", continent: "Asia", populationM: 22, economy: 45, infrastructure: 50, tourism: 80, significance: 50, divisions: [{ id: "LK-1", name: "Western Province", weight: 145 }, { id: "LK-2", name: "Central Province" }, { id: "LK-3", name: "Southern Province" }, { id: "LK-4", name: "Northern Province" }, { id: "LK-5", name: "Eastern Province" }, { id: "LK-6", name: "North Western" }, { id: "LK-7", name: "North Central" }, { id: "LK-8", name: "Uva" }, { id: "LK-9", name: "Sabaragamuwa" }] },
    { code: "LT", name: "Lithuania", continent: "Europe", populationM: 3, economy: 70, infrastructure: 80, tourism: 72, significance: 52, divisions: [{ id: "LT-VL", name: "Vilnius", weight: 140 }, { id: "LT-KU", name: "Kaunas", weight: 135 }, { id: "LT-KL", name: "Klaipeda", weight: 135 }, { id: "LT-SA", name: "Siauliai" }, { id: "LT-PN", name: "Panevezys" }, { id: "LT-AL", name: "Alytus" }, { id: "LT-MR", name: "Marijampole" }, { id: "LT-TA", name: "Taurage" }, { id: "LT-TE", name: "Telsiai" }, { id: "LT-UT", name: "Utena" }] },
    { code: "LU", name: "Luxembourg", continent: "Europe", populationM: 1, economy: 92, infrastructure: 95, tourism: 80, significance: 72, divisions: [{ id: "LU-LU", name: "Luxembourg City", weight: 150 }, { id: "LU-ES", name: "Esch-sur-Alzette" }, { id: "LU-DI", name: "Diekirch" }, { id: "LU-GR", name: "Grevenmacher" }, { id: "LU-CA", name: "Capellen" }, { id: "LU-CL", name: "Clervaux" }, { id: "LU-EC", name: "Echternach" }, { id: "LU-ME", name: "Mersch" }, { id: "LU-RD", name: "Redange" }, { id: "LU-RM", name: "Remich" }, { id: "LU-VD", name: "Vianden" }, { id: "LU-WI", name: "Wiltz" }] },
    { code: "LV", name: "Latvia", continent: "Europe", populationM: 2, economy: 68, infrastructure: 78, tourism: 75, significance: 50, divisions: [{ id: "LV-RIX", name: "Riga", weight: 140 }, { id: "LV-DGV", name: "Daugavpils" }, { id: "LV-LPX", name: "Liepaja" }, { id: "LV-VMR", name: "Valmiera" }, { id: "LV-JUR", name: "Jurmala", weight: 135 }, { id: "LV-VEN", name: "Ventspils" }, { id: "LV-REZ", name: "Rezekne" }, { id: "LV-JEL", name: "Jelgava" }] },
    { code: "MA", name: "Morocco", continent: "Africa", populationM: 38, economy: 50, infrastructure: 58, tourism: 92, significance: 52, divisions: [{ id: "MA-CAS", name: "Casablanca-Settat", weight: 150 }, { id: "MA-RAB", name: "Rabat-Sale-Kenitra", weight: 140 }, { id: "MA-MAR", name: "Marrakech-Safi", weight: 165 }, { id: "MA-TNG", name: "Tanger-Tetouan-Al Hoceima", weight: 145 }, { id: "MA-FES", name: "Fes-Meknes", weight: 140 }, { id: "MA-ORI", name: "Oriental" }, { id: "MA-BSM", name: "Beni Mellal-Khenifra" }, { id: "MA-DRA", name: "Draa-Tafilalet", weight: 140 }, { id: "MA-SOU", name: "Souss-Massa", weight: 150 }, { id: "MA-GUN", name: "Guelmim-Oued Noun" }, { id: "MA-LAA", name: "Laayoune-Sakia El Hamra" }, { id: "MA-DAK", name: "Dakhla-Oued Ed-Dahab" }] },
    { code: "MD", name: "Moldova", continent: "Europe", populationM: 3, economy: 42, infrastructure: 48, tourism: 68, significance: 42, divisions: [{ id: "MD-CU", name: "Chisinau", weight: 135 }, { id: "MD-BA", name: "Balti" }, { id: "MD-TI", name: "Tiraspol" }, { id: "MD-BD", name: "Bender" }, { id: "MD-AN", name: "Anenii Noi" }, { id: "MD-CA", name: "Cahul" }, { id: "MD-OR", name: "Orhei" }, { id: "MD-SO", name: "Soroca" }, { id: "MD-UN", name: "Ungheni" }] },
    { code: "MM", name: "Myanmar", continent: "Asia", populationM: 54, economy: 32, infrastructure: 28, tourism: 65, significance: 42, divisions: [{ id: "MM-06", name: "Yangon", weight: 140 }, { id: "MM-04", name: "Mandalay" }, { id: "MM-01", name: "Sagaing" }, { id: "MM-05", name: "Tanintharyi" }, { id: "MM-07", name: "Bago" }, { id: "MM-03", name: "Magway" }, { id: "MM-02", name: "Bago" }] },
    { code: "MN", name: "Mongolia", continent: "Asia", populationM: 3, economy: 42, infrastructure: 38, tourism: 65, significance: 42, divisions: [{ id: "MN-1", name: "Ulaanbaatar", weight: 145 }, { id: "MN-73", name: "Arkhangai" }, { id: "MN-71", name: "Bayan-Ulgii" }, { id: "MN-43", name: "Khovd" }, { id: "MN-49", name: "Selenge" }, { id: "MN-61", name: "Dornod" }, { id: "MN-63", name: "Dornogovi" }, { id: "MN-65", name: "Govisumber" }] },
    { code: "MT", name: "Malta", continent: "Europe", populationM: 1, economy: 60, infrastructure: 75, tourism: 92, significance: 45, divisions: [{ id: "MT-01", name: "Attard" }, { id: "MT-02", name: "Balzan" }, { id: "MT-03", name: "Birgu" }, { id: "MT-04", name: "Birkirkara" }, { id: "MT-05", name: "Birzebbuga" }, { id: "MT-06", name: "Bormla" }, { id: "MT-07", name: "Dingli" }, { id: "MT-08", name: "Fgura" }, { id: "MT-09", name: "Floriana" }, { id: "MT-10", name: "Fontana" }, { id: "MT-11", name: "Gudja" }, { id: "MT-12", name: "Gzira" }, { id: "MT-13", name: "Ghajnsielem" }, { id: "MT-14", name: "Gharb" }, { id: "MT-15", name: "Gharghur" }, { id: "MT-16", name: "Ghasri" }, { id: "MT-17", name: "Ghaxaq" }, { id: "MT-18", name: "Gudja" }, { id: "MT-19", name: "Iklin" }, { id: "MT-20", name: "Isla" }, { id: "MT-21", name: "Kalkara" }, { id: "MT-22", name: "Kercem" }, { id: "MT-23", name: "Kirkop" }, { id: "MT-24", name: "Lija" }, { id: "MT-25", name: "Luqa" }, { id: "MT-26", name: "Marsa" }, { id: "MT-27", name: "Marsaskala" }, { id: "MT-28", name: "Marsaxlokk" }, { id: "MT-29", name: "Mdina" }, { id: "MT-30", name: "Mellieha" }, { id: "MT-31", name: "Mgarr" }, { id: "MT-32", name: "Mosta" }, { id: "MT-33", name: "Mqabba" }, { id: "MT-34", name: "Msida" }, { id: "MT-35", name: "Mtarfa" }, { id: "MT-36", name: "Munxar" }, { id: "MT-37", name: "Nadur" }, { id: "MT-38", name: "Naxxar" }, { id: "MT-39", name: "Paola" }, { id: "MT-40", name: "Pembroke" }, { id: "MT-41", name: "Pieta" }, { id: "MT-42", name: "Qala" }, { id: "MT-43", name: "Qormi" }, { id: "MT-44", name: "Qrendi" }, { id: "MT-45", name: "Rabat" }, { id: "MT-46", name: "Rabat" }, { id: "MT-47", name: "Safi" }, { id: "MT-48", name: "St. Julian's" }, { id: "MT-49", name: "San Gwann" }, { id: "MT-50", name: "Santa Lucija" }, { id: "MT-51", name: "St. Paul's Bay" }, { id: "MT-52", name: "Sannat" }, { id: "MT-53", name: "Santa Venera" }, { id: "MT-54", name: "Siggiewi" }, { id: "MT-55", name: "Sliema" }, { id: "MT-56", name: "Swieqi" }, { id: "MT-57", name: "Tarxien" }, { id: "MT-58", name: "Ta' Xbiex" }, { id: "MT-59", name: "Valletta" }, { id: "MT-60", name: "Xaghra" }, { id: "MT-61", name: "Xewkija" }, { id: "MT-62", name: "Xghajra" }, { id: "MT-63", name: "Zabbar" }, { id: "MT-64", name: "Zebbug" }, { id: "MT-65", name: "Zebbug" }, { id: "MT-66", name: "Zejtun" }, { id: "MT-67", name: "Zurrieq" }] },
    { code: "MX", name: "Mexico", continent: "North America", populationM: 129, economy: 62, infrastructure: 60, tourism: 85, significance: 70, divisions: [{ id: "MX-CMX", name: "Ciudad de Mexico", weight: 170 }, { id: "MX-JAL", name: "Jalisco", weight: 115 }, { id: "MX-NLE", name: "Nuevo Leon", weight: 115 }, { id: "MX-QRO", name: "Quintana Roo", weight: 155 }, { id: "MX-YUC", name: "Yucatan", weight: 120 }, { id: "MX-PUE", name: "Puebla" }, { id: "MX-GUA", name: "Guanajuato" }, { id: "MX-VER", name: "Veracruz" }, { id: "MX-CHH", name: "Chihuahua" }, { id: "MX-BCN", name: "Baja California" }, { id: "MX-BCS", name: "Baja California Sur", weight: 125 }, { id: "MX-SON", name: "Sonora" }, { id: "MX-OAX", name: "Oaxaca" }, { id: "MX-MIC", name: "Michoacan" }, { id: "MX-SIN", name: "Sinaloa" }, { id: "MX-TAM", name: "Tamaulipas" }, { id: "MX-COA", name: "Coahuila" }, { id: "MX-HID", name: "Hidalgo" }, { id: "MX-MOR", name: "Morelos" }, { id: "MX-TLA", name: "Tlaxcala" }, { id: "MX-AGS", name: "Aguascalientes" }, { id: "MX-COL", name: "Colima" }, { id: "MX-DUR", name: "Durango" }, { id: "MX-GRO", name: "Guerrero" }, { id: "MX-NAY", name: "Nayarit" }, { id: "MX-QUE", name: "Queretaro" }, { id: "MX-SLP", name: "San Luis Potosi" }, { id: "MX-TAB", name: "Tabasco" }, { id: "MX-CAM", name: "Campeche" }, { id: "MX-CHP", name: "Chiapas" }, { id: "MX-ZAC", name: "Zacatecas" }] },
    { code: "MY", name: "Malaysia", continent: "Asia", populationM: 34, economy: 70, infrastructure: 72, tourism: 85, significance: 60, divisions: [{ id: "MY-14", name: "Kuala Lumpur", weight: 170 }, { id: "MY-10", name: "Selangor", weight: 130 }, { id: "MY-07", name: "Penang", weight: 135 }, { id: "MY-01", name: "Johor" }, { id: "MY-12", name: "Sabah" }, { id: "MY-13", name: "Sarawak" }, { id: "MY-06", name: "Pahang" }, { id: "MY-09", name: "Perlis" }, { id: "MY-04", name: "Melaka" }, { id: "MY-08", name: "Perak" }, { id: "MY-02", name: "Kedah" }, { id: "MY-03", name: "Kelantan" }, { id: "MY-11", name: "Terengganu" }, { id: "MY-05", name: "Negeri Sembilan" }, { id: "MY-15", name: "Labuan" }] },
    { code: "MZ", name: "Mozambique", continent: "Africa", populationM: 33, economy: 32, infrastructure: 28, tourism: 80, significance: 40, divisions: [{ id: "MZ-MPM", name: "Maputo City", weight: 140 }, { id: "MZ-MPL", name: "Maputo Province" }, { id: "MZ-G", name: "Gaza" }, { id: "MZ-I", name: "Inhambane", weight: 135 }, { id: "MZ-S", name: "Sofala" }, { id: "MZ-T", name: "Tete" }, { id: "MZ-B", name: "Manica" }, { id: "MZ-N", name: "Nampula" }, { id: "MZ-A", name: "Niassa" }, { id: "MZ-Q", name: "Zambezia" }, { id: "MZ-P", name: "Cabo Delgado", weight: 135 }] },
    { code: "NG", name: "Nigeria", continent: "Africa", populationM: 223, economy: 45, infrastructure: 32, tourism: 50, significance: 52, divisions: [{ id: "NG-LA", name: "Lagos", weight: 155 }, { id: "NG-FC", name: "Abuja", weight: 135 }, { id: "NG-KN", name: "Kano" }, { id: "NG-RI", name: "Rivers" }, { id: "NG-OG", name: "Ogun" }, { id: "NG-OY", name: "Oyo" }, { id: "NG-KD", name: "Kaduna" }, { id: "NG-AN", name: "Anambra" }, { id: "NG-DE", name: "Delta" }, { id: "NG-ED", name: "Edo" }, { id: "NG-EN", name: "Enugu" }, { id: "NG-AB", name: "Abia" }, { id: "NG-IM", name: "Imo" }, { id: "NG-KW", name: "Kwara" }, { id: "NG-PL", name: "Plateau" }, { id: "NG-BO", name: "Borno" }] },
    { code: "NI", name: "Nicaragua", continent: "North America", populationM: 7, economy: 35, infrastructure: 35, tourism: 80, significance: 42, divisions: [{ id: "NI-MN", name: "Managua", weight: 140 }, { id: "NI-LE", name: "Leon" }, { id: "NI-GR", name: "Granada", weight: 140 }, { id: "NI-MA", name: "Masaya" }, { id: "NI-CI", name: "Chinandega" }, { id: "NI-AS", name: "Atlantico Sur" }, { id: "NI-AN", name: "Atlantico Norte" }, { id: "NI-RI", name: "Rivas", weight: 140 }] },
    { code: "NL", name: "Netherlands", continent: "Europe", populationM: 18, economy: 90, infrastructure: 95, tourism: 85, significance: 80, divisions: [{ id: "NL-NH", name: "North Holland", weight: 150 }, { id: "NL-ZH", name: "South Holland", weight: 135 }, { id: "NL-UT", name: "Utrecht" }, { id: "NL-NB", name: "North Brabant" }, { id: "NL-GE", name: "Gelderland" }, { id: "NL-LI", name: "Limburg" }, { id: "NL-OV", name: "Overijssel" }, { id: "NL-FR", name: "Friesland" }, { id: "NL-GR", name: "Groningen" }, { id: "NL-DR", name: "Drenthe" }, { id: "NL-FL", name: "Flevoland" }, { id: "NL-ZE", name: "Zealand" }] },
    { code: "NO", name: "Norway", continent: "Europe", populationM: 5, economy: 92, infrastructure: 92, tourism: 88, significance: 68, divisions: [{ id: "NO-03", name: "Oslo", weight: 160 }, { id: "NO-11", name: "Rogaland" }, { id: "NO-46", name: "Vestland", weight: 150 }, { id: "NO-15", name: "More og Romsdal" }, { id: "NO-18", name: "Nordland", weight: 145 }, { id: "NO-50", name: "Trondelag" }, { id: "NO-31", name: "Ostfold" }, { id: "NO-30", name: "Viken" }, { id: "NO-54", name: "Troms og Finnmark", weight: 140 }] },
    { code: "NP", name: "Nepal", continent: "Asia", populationM: 31, economy: 38, infrastructure: 32, tourism: 78, significance: 48, divisions: [{ id: "NP-BA", name: "Bagmati", weight: 140 }, { id: "NP-GA", name: "Gandaki" }, { id: "NP-LU", name: "Lumbini" }, { id: "NP-KO", name: "Koshi" }, { id: "NP-MA", name: "Madhesh" }, { id: "NP-KA", name: "Karnali" }, { id: "NP-SU", name: "Sudurpashchim" }] },
    { code: "NZ", name: "New Zealand", continent: "Oceania", populationM: 5, economy: 78, infrastructure: 88, tourism: 88, significance: 60, divisions: [{ id: "NZ-AUK", name: "Auckland", weight: 130 }, { id: "NZ-WGN", name: "Wellington", weight: 120 }, { id: "NZ-CAN", name: "Canterbury" }, { id: "NZ-OTA", name: "Otago", weight: 120 }, { id: "NZ-BOP", name: "Bay of Plenty" }, { id: "NZ-WKO", name: "Waikato" }, { id: "NZ-STL", name: "Southland" }] },
    { code: "OM", name: "Oman", continent: "Asia", populationM: 5, economy: 68, infrastructure: 72, tourism: 82, significance: 62, divisions: [{ id: "OM-MA", name: "Muscat", weight: 150 }, { id: "OM-DH", name: "Dhofar", weight: 140 }, { id: "OM-BS", name: "Al Batinah North" }, { id: "OM-BJ", name: "Al Batinah South" }, { id: "OM-DA", name: "Ad Dakhiliyah" }, { id: "OM-SH", name: "Ash Sharqiyah North" }, { id: "OM-SJ", name: "Ash Sharqiyah South" }, { id: "OM-ZA", name: "Ad Dhahirah" }, { id: "OM-BU", name: "Al Buraymi" }, { id: "OM-WU", name: "Al Wusta" }, { id: "OM-ZU", name: "Dhofar" }] },
    { code: "PA", name: "Panama", continent: "North America", populationM: 4, economy: 62, infrastructure: 68, tourism: 85, significance: 52, divisions: [{ id: "PA-8", name: "Panama", weight: 145 }, { id: "PA-10", name: "Panama West" }, { id: "PA-3", name: "Colon" }, { id: "PA-4", name: "Chiriqui" }, { id: "PA-2", name: "Cocle" }, { id: "PA-6", name: "Herrera" }, { id: "PA-7", name: "Los Santos" }, { id: "PA-9", name: "Veraguas" }, { id: "PA-1", name: "Bocas del Toro" }, { id: "PA-5", name: "Darien" }, { id: "PA-EM", name: "Embera" }, { id: "PA-KY", name: "Guna Yala" }] },
    { code: "PE", name: "Peru", continent: "South America", populationM: 34, economy: 48, infrastructure: 45, tourism: 80, significance: 52, divisions: [{ id: "PE-LIM", name: "Lima", weight: 160 }, { id: "PE-CUS", name: "Cusco", weight: 170 }, { id: "PE-ARE", name: "Arequipa" }, { id: "PE-LAL", name: "La Libertad" }, { id: "PE-PIU", name: "Piura" }, { id: "PE-JUN", name: "Junin" }, { id: "PE-LAM", name: "Lambayeque" }, { id: "PE-ANC", name: "Ancash" }, { id: "PE-ICA", name: "Ica" }, { id: "PE-PUN", name: "Puno" }, { id: "PE-LOR", name: "Loreto" }] },
    { code: "PH", name: "Philippines", continent: "Asia", populationM: 117, economy: 50, infrastructure: 42, tourism: 88, significance: 58, divisions: [{ id: "PH-NCR", name: "Metro Manila", weight: 165 }, { id: "PH-CEB", name: "Cebu", weight: 140 }, { id: "PH-BLK", name: "Bulacan" }, { id: "PH-CAV", name: "Cavite" }, { id: "PH-LAG", name: "Laguna" }, { id: "PH-PAM", name: "Pampanga" }, { id: "PH-DAV", name: "Davao del Sur" }, { id: "PH-ALB", name: "Albay" }, { id: "PH-BOH", name: "Bohol", weight: 120 }, { id: "PH-PLW", name: "Palawan", weight: 150 }, { id: "PH-ILN", name: "Ilocos Norte" }, { id: "PH-ILI", name: "Iloilo" }, { id: "PH-NEC", name: "Negros Occidental" }, { id: "PH-ZMB", name: "Zambales" }, { id: "PH-QUE", name: "Quezon" }, { id: "PH-RIZ", name: "Rizal" }, { id: "PH-SOR", name: "Sorsogon" }] },
    { code: "PK", name: "Pakistan", continent: "Asia", populationM: 240, economy: 42, infrastructure: 35, tourism: 55, significance: 58, divisions: [{ id: "PK-SD", name: "Sindh", weight: 140 }, { id: "PK-PB", name: "Punjab", weight: 110 }, { id: "PK-KP", name: "Khyber Pakhtunkhwa" }, { id: "PK-BA", name: "Balochistan" }, { id: "PK-IS", name: "Islamabad" }, { id: "PK-GB", name: "Gilgit-Baltistan" }, { id: "PK-JK", name: "Azad Kashmir" }] },
    { code: "PL", name: "Poland", continent: "Europe", populationM: 37, economy: 68, infrastructure: 72, tourism: 72, significance: 60, divisions: [{ id: "PL-MZ", name: "Masovia", weight: 140 }, { id: "PL-MA", name: "Lesser Poland", weight: 130 }, { id: "PL-SL", name: "Silesia" }, { id: "PL-DS", name: "Lower Silesia" }, { id: "PL-WP", name: "Greater Poland" }, { id: "PL-PM", name: "Pomerania", weight: 130 }, { id: "PL-LD", name: "Lodz" }, { id: "PL-LB", name: "Lubusz" }, { id: "PL-KP", name: "Kuyavia-Pomerania" }, { id: "PL-WN", name: "Warmia-Masuria" }, { id: "PL-ZP", name: "West Pomerania" }, { id: "PL-PD", name: "Podlaskie" }, { id: "PL-LU", name: "Lublin" }, { id: "PL-SK", name: "Swietokrzyskie" }, { id: "PL-OP", name: "Opole" }, { id: "PL-PK", name: "Subcarpathia" }] },
    { code: "PT", name: "Portugal", continent: "Europe", populationM: 10, economy: 70, infrastructure: 82, tourism: 95, significance: 68, divisions: [{ id: "PT-11", name: "Lisbon", weight: 180 }, { id: "PT-13", name: "Porto", weight: 150 }, { id: "PT-08", name: "Faro", weight: 160 }, { id: "PT-20", name: "Azores" }, { id: "PT-30", name: "Madeira", weight: 150 }, { id: "PT-01", name: "Aveiro" }, { id: "PT-03", name: "Braga" }, { id: "PT-06", name: "Coimbra" }, { id: "PT-10", name: "Leiria" }, { id: "PT-14", name: "Santarem" }, { id: "PT-15", name: "Setubal" }, { id: "PT-18", name: "Viseu" }] },
    { code: "PY", name: "Paraguay", continent: "South America", populationM: 7, economy: 45, infrastructure: 48, tourism: 72, significance: 48, divisions: [{ id: "PY-ASU", name: "Asuncion", weight: 145 }, { id: "PY-1", name: "Concepcion" }, { id: "PY-2", name: "San Pedro" }, { id: "PY-3", name: "Cordillera" }, { id: "PY-4", name: "Guaira" }, { id: "PY-5", name: "Caaguazu" }, { id: "PY-6", name: "Caazapa" }, { id: "PY-7", name: "Itapua" }, { id: "PY-8", name: "Misiones" }, { id: "PY-9", name: "Paraguari" }, { id: "PY-10", name: "Alto Parana" }, { id: "PY-11", name: "Central" }, { id: "PY-12", name: "Neembucu" }, { id: "PY-13", name: "Amambay" }, { id: "PY-14", name: "Canindeyu" }, { id: "PY-15", name: "Presidente Hayes" }, { id: "PY-16", name: "Alto Paraguay" }, { id: "PY-19", name: "Boqueron" }] },
    { code: "QA", name: "Qatar", continent: "Asia", populationM: 3, economy: 90, infrastructure: 94, tourism: 85, significance: 80, divisions: [{ id: "QA-DA", name: "Doha", weight: 180 }, { id: "QA-KH", name: "Al Khor" }, { id: "QA-RA", name: "Al Rayyan" }, { id: "QA-WA", name: "Al Wakrah" }, { id: "QA-MS", name: "Madinat ash Shamal" }, { id: "QA-ZA", name: "Al Daayen" }] },
    { code: "RO", name: "Romania", continent: "Europe", populationM: 19, economy: 58, infrastructure: 60, tourism: 72, significance: 52, divisions: [{ id: "RO-B", name: "Bucharest", weight: 150 }, { id: "RO-CJ", name: "Cluj" }, { id: "RO-TM", name: "Timis" }, { id: "RO-IS", name: "Iasi" }, { id: "RO-BV", name: "Brasov", weight: 130 }, { id: "RO-CT", name: "Constanta", weight: 135 }, { id: "RO-BH", name: "Bihor" }, { id: "RO-PH", name: "Prahova" }, { id: "RO-SB", name: "Sibiu", weight: 130 }, { id: "RO-AG", name: "Arges" }, { id: "RO-DJ", name: "Dolj" }, { id: "RO-GJ", name: "Gorj" }, { id: "RO-MS", name: "Mures" }, { id: "RO-BN", name: "Bistrita-Nasaud" }, { id: "RO-SV", name: "Suceava" }, { id: "RO-BC", name: "Bacau" }] },
    { code: "RS", name: "Serbia", continent: "Europe", populationM: 7, economy: 52, infrastructure: 58, tourism: 72, significance: 48, divisions: [{ id: "RS-00", name: "Belgrade", weight: 145 }, { id: "RS-01", name: "North Backa" }, { id: "RS-02", name: "Central Banat" }, { id: "RS-03", name: "North Banat" }, { id: "RS-04", name: "South Banat" }, { id: "RS-05", name: "West Backa" }, { id: "RS-06", name: "South Backa" }, { id: "RS-07", name: "Srem" }, { id: "RS-08", name: "Macva" }, { id: "RS-09", name: "Kolubara" }, { id: "RS-10", name: "Podunavlje" }, { id: "RS-11", name: "Branicevo" }, { id: "RS-12", name: "Sumadija" }, { id: "RS-13", name: "Pomoravlje" }, { id: "RS-14", name: "Bor" }, { id: "RS-15", name: "Zajecar" }, { id: "RS-16", name: "Zlatibor" }, { id: "RS-17", name: "Moravica" }, { id: "RS-18", name: "Raska" }, { id: "RS-19", name: "Rasina" }, { id: "RS-20", name: "Nisava" }, { id: "RS-21", name: "Toplica" }, { id: "RS-22", name: "Pirot" }, { id: "RS-23", name: "Jablanica" }, { id: "RS-24", name: "Pcinja" }, { id: "RS-25", name: "Kosovo" }, { id: "RS-26", name: "Pec" }, { id: "RS-27", name: "Prizren" }, { id: "RS-28", name: "Kosovska Mitrovica" }, { id: "RS-29", name: "Kosovo-Pomoravlje" }] },
    { code: "RU", name: "Russia", continent: "Europe", populationM: 144, economy: 60, infrastructure: 55, tourism: 50, significance: 80, divisions: [{ id: "RU-MOW", name: "Moscow", weight: 180 }, { id: "RU-SPE", name: "Saint Petersburg", weight: 150 }, { id: "RU-MOS", name: "Moscow Oblast" }, { id: "RU-KDA", name: "Krasnodar Krai", weight: 120 }, { id: "RU-SVE", name: "Sverdlovsk Oblast" }, { id: "RU-TA", name: "Tatarstan" }, { id: "RU-NVS", name: "Novosibirsk Oblast" }, { id: "RU-KYA", name: "Krasnoyarsk Krai" }, { id: "RU-PRI", name: "Primorsky Krai" }, { id: "RU-ROS", name: "Rostov Oblast" }, { id: "RU-BA", name: "Bashkortostan" }, { id: "RU-CHE", name: "Chelyabinsk Oblast" }, { id: "RU-SAM", name: "Samara Oblast" }, { id: "RU-NIZ", name: "Nizhny Novgorod Oblast" }, { id: "RU-KHM", name: "Khanty-Mansi" }, { id: "RU-IRA", name: "Irkutsk Oblast" }, { id: "RU-ALT", name: "Altai Krai" }, { id: "RU-VGG", name: "Volgograd Oblast" }, { id: "RU-PER", name: "Perm Krai" }, { id: "RU-SAR", name: "Saratov Oblast" }] },
    { code: "RW", name: "Rwanda", continent: "Africa", populationM: 14, economy: 38, infrastructure: 35, tourism: 85, significance: 42, divisions: [{ id: "RW-01", name: "Kigali", weight: 145 }, { id: "RW-02", name: "Eastern" }, { id: "RW-03", name: "Northern" }, { id: "RW-04", name: "Western" }, { id: "RW-05", name: "Southern" }] },
    { code: "SA", name: "Saudi Arabia", continent: "Asia", populationM: 37, economy: 78, infrastructure: 82, tourism: 78, significance: 78, divisions: [{ id: "SA-01", name: "Riyadh", weight: 160 }, { id: "SA-02", name: "Makkah", weight: 165 }, { id: "SA-03", name: "Madinah", weight: 160 }, { id: "SA-04", name: "Eastern Province" }, { id: "SA-05", name: "Al-Qassim" }, { id: "SA-06", name: "Hail" }, { id: "SA-07", name: "Tabuk" }, { id: "SA-08", name: "Northern Borders" }, { id: "SA-09", name: "Jazan" }, { id: "SA-10", name: "Najran" }, { id: "SA-11", name: "Al Bahah" }, { id: "SA-12", name: "Al Jouf" }, { id: "SA-14", name: "Asir" }] },
    { code: "SE", name: "Sweden", continent: "Europe", populationM: 11, economy: 88, infrastructure: 92, tourism: 78, significance: 72, divisions: [{ id: "SE-AB", name: "Stockholm", weight: 150 }, { id: "SE-O", name: "Vastra Gotaland" }, { id: "SE-M", name: "Skane" }, { id: "SE-C", name: "Uppsala" }, { id: "SE-D", name: "Sodermanland" }, { id: "SE-E", name: "Ostergotland" }, { id: "SE-F", name: "Jonkoping" }, { id: "SE-N", name: "Halland" }, { id: "SE-W", name: "Dalarna" }, { id: "SE-BD", name: "Norrbotten" }, { id: "SE-AC", name: "Vasterbotten" }, { id: "SE-Y", name: "Vasternorrland" }] },
    { code: "SG", name: "Singapore", continent: "Asia", populationM: 6, economy: 98, infrastructure: 100, tourism: 88, significance: 88 },
    { code: "SK", name: "Slovakia", continent: "Europe", populationM: 5, economy: 60, infrastructure: 68, tourism: 78, significance: 52, divisions: [{ id: "SK-BL", name: "Bratislava", weight: 140 }, { id: "SK-KI", name: "Kosice" }, { id: "SK-PV", name: "Presov" }, { id: "SK-ZI", name: "Zilina" }, { id: "SK-NI", name: "Nitra" }, { id: "SK-TA", name: "Trnava" }, { id: "SK-BC", name: "Banska Bystrica" }, { id: "SK-TC", name: "Trencin" }] },
    { code: "SN", name: "Senegal", continent: "Africa", populationM: 18, economy: 42, infrastructure: 40, tourism: 78, significance: 45, divisions: [{ id: "SN-DK", name: "Dakar", weight: 145 }, { id: "SN-TH", name: "Thies" }, { id: "SN-DB", name: "Diourbel" }, { id: "SN-FK", name: "Fatick" }, { id: "SN-KL", name: "Kaolack" }, { id: "SN-LG", name: "Louga" }, { id: "SN-MT", name: "Matam" }, { id: "SN-SL", name: "Saint-Louis", weight: 140 }, { id: "SN-TC", name: "Tambacounda" }, { id: "SN-ZG", name: "Ziguinchor", weight: 140 }, { id: "SN-KE", name: "Kedougou" }, { id: "SN-KD", name: "Kolda" }] },
    { code: "SR", name: "Suriname", continent: "South America", populationM: 1, economy: 40, infrastructure: 42, tourism: 65, significance: 35, divisions: [{ id: "SR-PM", name: "Paramaribo", weight: 140 }, { id: "SR-WA", name: "Wanica" }, { id: "SR-NI", name: "Nickerie" }, { id: "SR-CR", name: "Coronie" }, { id: "SR-SA", name: "Saramacca" }, { id: "SR-CO", name: "Commewijne" }, { id: "SR-MA", name: "Marowijne" }, { id: "SR-BR", name: "Brokopondo" }, { id: "SR-PR", name: "Para" }, { id: "SR-SI", name: "Sipaliwini" }] },
    { code: "SV", name: "El Salvador", continent: "North America", populationM: 6, economy: 42, infrastructure: 45, tourism: 78, significance: 45, divisions: [{ id: "SV-SS", name: "San Salvador", weight: 140 }, { id: "SV-SO", name: "Sonsonate" }, { id: "SV-SA", name: "Santa Ana" }, { id: "SV-SM", name: "San Miguel" }, { id: "SV-LI", name: "La Libertad", weight: 140 }, { id: "SV-UN", name: "La Union" }, { id: "SV-CA", name: "Cabanas" }, { id: "SV-CH", name: "Chalatenango" }, { id: "SV-CU", name: "Cuscatlan" }, { id: "SV-MO", name: "Morazan" }, { id: "SV-PA", name: "La Paz" }, { id: "SV-AH", name: "Ahuachapan" }, { id: "SV-US", name: "Usulutan" }, { id: "SV-SV", name: "San Vicente" }] },
    { code: "TH", name: "Thailand", continent: "Asia", populationM: 72, economy: 60, infrastructure: 68, tourism: 90, significance: 62, divisions: [{ id: "TH-10", name: "Bangkok", weight: 175 }, { id: "TH-83", name: "Phuket", weight: 185 }, { id: "TH-40", name: "Chon Buri", weight: 150 }, { id: "TH-50", name: "Chiang Mai", weight: 150 }, { id: "TH-20", name: "Chonburi" }, { id: "TH-30", name: "Nakhon Ratchasima" }, { id: "TH-80", name: "Surat Thani", weight: 140 }, { id: "TH-42", name: "Krabi", weight: 150 }, { id: "TH-57", name: "Rayong" }, { id: "TH-77", name: "Songkhla" }, { id: "TH-90", name: "Prachuap Khiri Khan" }, { id: "TH-63", name: "Phitsanulok" }] },
    { code: "TN", name: "Tunisia", continent: "Africa", populationM: 12, economy: 45, infrastructure: 52, tourism: 92, significance: 48, divisions: [{ id: "TN-11", name: "Tunis", weight: 145 }, { id: "TN-12", name: "Ariana" }, { id: "TN-13", name: "Ben Arous" }, { id: "TN-21", name: "Nabeul", weight: 140 }, { id: "TN-51", name: "Sousse", weight: 140 }, { id: "TN-52", name: "Monastir" }, { id: "TN-61", name: "Sfax" }, { id: "TN-81", name: "Gabes" }, { id: "TN-82", name: "Medenine", weight: 140 }, { id: "TN-83", name: "Tataouine" }, { id: "TN-71", name: "Gafsa" }, { id: "TN-73", name: "Kebili" }] },
    { code: "TR", name: "Turkiye", continent: "Asia", populationM: 85, economy: 66, infrastructure: 68, tourism: 92, significance: 62, divisions: [{ id: "TR-34", name: "Istanbul", weight: 180 }, { id: "TR-06", name: "Ankara", weight: 140 }, { id: "TR-35", name: "Izmir", weight: 150 }, { id: "TR-07", name: "Antalya", weight: 160 }, { id: "TR-48", name: "Mugla", weight: 150 }, { id: "TR-16", name: "Bursa" }, { id: "TR-01", name: "Adana" }, { id: "TR-42", name: "Konya" }, { id: "TR-38", name: "Kayseri" }, { id: "TR-20", name: "Denizli" }, { id: "TR-61", name: "Trabzon" }, { id: "TR-55", name: "Samsun" }, { id: "TR-21", name: "Diyarbakir" }, { id: "TR-27", name: "Gaziantep" }, { id: "TR-31", name: "Hatay" }] },
    { code: "TT", name: "Trinidad and Tobago", continent: "North America", populationM: 2, economy: 52, infrastructure: 58, tourism: 82, significance: 45, divisions: [{ id: "TT-POS", name: "Port of Spain", weight: 140 }, { id: "TT-SFO", name: "San Fernando" }, { id: "TT-CHA", name: "Chaguanas" }, { id: "TT-ARI", name: "Arima" }, { id: "TT-PTF", name: "Point Fortin" }, { id: "TT-SIP", name: "Siparia" }, { id: "TT-TUP", name: "Tunapuna-Piarco" }, { id: "TT-COU", name: "Couva-Tabaquite-Talparo" }, { id: "TT-PED", name: "Penal-Debe" }, { id: "TT-PRT", name: "Princes Town" }, { id: "TT-SGE", name: "Sangre Grande" }, { id: "TT-RCM", name: "Rio Claro-Mayaro" }, { id: "TT-TOB", name: "Tobago", weight: 140 }] },
    { code: "TZ", name: "Tanzania", continent: "Africa", populationM: 67, economy: 42, infrastructure: 38, tourism: 88, significance: 48, divisions: [{ id: "TZ-03", name: "Dar es Salaam", weight: 145 }, { id: "TZ-26", name: "Zanzibar", weight: 150 }, { id: "TZ-01", name: "Arusha", weight: 150 }, { id: "TZ-25", name: "Mwanza" }, { id: "TZ-12", name: "Kilimanjaro" }, { id: "TZ-14", name: "Mbeya" }, { id: "TZ-16", name: "Morogoro" }, { id: "TZ-20", name: "Pemba" }, { id: "TZ-21", name: "Pwani" }, { id: "TZ-22", name: "Rukwa" }, { id: "TZ-23", name: "Ruvuma" }, { id: "TZ-24", name: "Shinyanga" }, { id: "TZ-27", name: "Kagera" }, { id: "TZ-28", name: "Kigoma" }, { id: "TZ-29", name: "Lindi" }, { id: "TZ-30", name: "Manyara" }, { id: "TZ-31", name: "Mara" }, { id: "TZ-32", name: "Mtwara" }, { id: "TZ-33", name: "Njombe" }, { id: "TZ-34", name: "Simiyu" }, { id: "TZ-35", name: "Songwe" }, { id: "TZ-36", name: "Tabora" }, { id: "TZ-37", name: "Tanga" }] },
    { code: "UA", name: "Ukraine", continent: "Europe", populationM: 38, economy: 42, infrastructure: 45, tourism: 60, significance: 52, divisions: [{ id: "UA-30", name: "Kyiv", weight: 150 }, { id: "UA-63", name: "Kharkiv" }, { id: "UA-46", name: "Lviv", weight: 130 }, { id: "UA-51", name: "Odesa", weight: 135 }, { id: "UA-12", name: "Dnipropetrovsk" }, { id: "UA-14", name: "Donetsk" }, { id: "UA-59", name: "Sumy" }, { id: "UA-56", name: "Rivne" }, { id: "UA-18", name: "Zhytomyr" }, { id: "UA-23", name: "Zaporizhzhia" }, { id: "UA-26", name: "Ivano-Frankivsk" }, { id: "UA-65", name: "Kherson" }, { id: "UA-68", name: "Khmelnytskyi" }, { id: "UA-71", name: "Cherkasy" }, { id: "UA-74", name: "Chernihiv" }, { id: "UA-77", name: "Chernivtsi" }, { id: "UA-35", name: "Kirovohrad" }, { id: "UA-32", name: "Kyiv Oblast" }, { id: "UA-53", name: "Poltava" }, { id: "UA-05", name: "Vinnytsia" }, { id: "UA-07", name: "Volyn" }, { id: "UA-21", name: "Zakarpattia" }, { id: "UA-61", name: "Ternopil" }, { id: "UA-48", name: "Mykolaiv" }] },
    { code: "UG", name: "Uganda", continent: "Africa", populationM: 48, economy: 38, infrastructure: 32, tourism: 80, significance: 42, divisions: [{ id: "UG-102", name: "Kampala", weight: 140 }, { id: "UG-101", name: "Wakiso" }, { id: "UG-104", name: "Mukono" }, { id: "UG-201", name: "Jinja" }, { id: "UG-401", name: "Mbarara" }, { id: "UG-403", name: "Kasese" }, { id: "UG-304", name: "Gulu" }, { id: "UG-306", name: "Lira" }, { id: "UG-206", name: "Soroti" }] },
    { code: "US", name: "United States", continent: "North America", populationM: 335, economy: 100, infrastructure: 90, tourism: 85, significance: 100, divisions: [{ id: "US-AL", name: "Alabama" }, { id: "US-AK", name: "Alaska" }, { id: "US-AZ", name: "Arizona" }, { id: "US-AR", name: "Arkansas" }, { id: "US-CA", name: "California", weight: 180 }, { id: "US-CO", name: "Colorado" }, { id: "US-CT", name: "Connecticut" }, { id: "US-DE", name: "Delaware" }, { id: "US-DC", name: "District of Columbia", weight: 220 }, { id: "US-FL", name: "Florida", weight: 150 }, { id: "US-GA", name: "Georgia" }, { id: "US-HI", name: "Hawaii", weight: 170 }, { id: "US-ID", name: "Idaho" }, { id: "US-IL", name: "Illinois", weight: 130 }, { id: "US-IN", name: "Indiana" }, { id: "US-IA", name: "Iowa" }, { id: "US-KS", name: "Kansas" }, { id: "US-KY", name: "Kentucky" }, { id: "US-LA", name: "Louisiana" }, { id: "US-ME", name: "Maine" }, { id: "US-MD", name: "Maryland" }, { id: "US-MA", name: "Massachusetts", weight: 140 }, { id: "US-MI", name: "Michigan" }, { id: "US-MN", name: "Minnesota" }, { id: "US-MS", name: "Mississippi" }, { id: "US-MO", name: "Missouri" }, { id: "US-MT", name: "Montana" }, { id: "US-NE", name: "Nebraska" }, { id: "US-NV", name: "Nevada", weight: 130 }, { id: "US-NH", name: "New Hampshire" }, { id: "US-NJ", name: "New Jersey", weight: 140 }, { id: "US-NM", name: "New Mexico" }, { id: "US-NY", name: "New York", weight: 200 }, { id: "US-NC", name: "North Carolina" }, { id: "US-ND", name: "North Dakota" }, { id: "US-OH", name: "Ohio" }, { id: "US-OK", name: "Oklahoma" }, { id: "US-OR", name: "Oregon" }, { id: "US-PA", name: "Pennsylvania", weight: 130 }, { id: "US-RI", name: "Rhode Island" }, { id: "US-SC", name: "South Carolina" }, { id: "US-SD", name: "South Dakota" }, { id: "US-TN", name: "Tennessee" }, { id: "US-TX", name: "Texas", weight: 165 }, { id: "US-UT", name: "Utah" }, { id: "US-VT", name: "Vermont" }, { id: "US-VA", name: "Virginia" }, { id: "US-WA", name: "Washington", weight: 135 }, { id: "US-WV", name: "West Virginia" }, { id: "US-WI", name: "Wisconsin" }, { id: "US-WY", name: "Wyoming" }] },
    { code: "UY", name: "Uruguay", continent: "South America", populationM: 3, economy: 62, infrastructure: 72, tourism: 80, significance: 55, divisions: [{ id: "UY-MO", name: "Montevideo", weight: 150 }, { id: "UY-CA", name: "Canelones" }, { id: "UY-MA", name: "Maldonado", weight: 155 }, { id: "UY-RO", name: "Rocha", weight: 145 }, { id: "UY-CO", name: "Colonia" }, { id: "UY-SA", name: "Salto" }, { id: "UY-PA", name: "Paysandu" }, { id: "UY-RN", name: "Rio Negro" }, { id: "UY-SJ", name: "San Jose" }, { id: "UY-FS", name: "Flores" }, { id: "UY-DU", name: "Durazno" }, { id: "UY-TA", name: "Tacuarembo" }, { id: "UY-RV", name: "Rivera" }, { id: "UY-AR", name: "Artigas" }, { id: "UY-CL", name: "Cerro Largo" }, { id: "UY-LA", name: "Lavalleja" }, { id: "UY-TT", name: "Treinta y Tres" }, { id: "UY-FD", name: "Florida" }, { id: "UY-SO", name: "Soriano" }] },
    { code: "UZ", name: "Uzbekistan", continent: "Asia", populationM: 36, economy: 40, infrastructure: 45, tourism: 72, significance: 48, divisions: [{ id: "UZ-TK", name: "Tashkent", weight: 145 }, { id: "UZ-SA", name: "Samarkand", weight: 150 }, { id: "UZ-BU", name: "Bukhara", weight: 145 }, { id: "UZ-AN", name: "Andijan" }, { id: "UZ-FA", name: "Fergana" }, { id: "UZ-NA", name: "Namangan" }, { id: "UZ-QA", name: "Kashkadarya" }, { id: "UZ-SU", name: "Surkhandarya" }, { id: "UZ-XO", name: "Khorezm", weight: 140 }, { id: "UZ-NW", name: "Navoiy" }, { id: "UZ-JI", name: "Jizzakh" }, { id: "UZ-SI", name: "Sirdaryo" }, { id: "UZ-QR", name: "Karakalpakstan" }] },
    { code: "VE", name: "Venezuela", continent: "South America", populationM: 28, economy: 35, infrastructure: 40, tourism: 72, significance: 50, divisions: [{ id: "VE-A", name: "Distrito Capital", weight: 145 }, { id: "VE-B", name: "Anzoategui" }, { id: "VE-C", name: "Apure" }, { id: "VE-D", name: "Aragua" }, { id: "VE-E", name: "Barinas" }, { id: "VE-F", name: "Bolivar" }, { id: "VE-G", name: "Carabobo" }, { id: "VE-H", name: "Cojedes" }, { id: "VE-I", name: "Falcon" }, { id: "VE-J", name: "Guarico" }, { id: "VE-K", name: "Lara" }, { id: "VE-L", name: "Merida", weight: 140 }, { id: "VE-M", name: "Miranda" }, { id: "VE-N", name: "Monagas" }, { id: "VE-O", name: "Nueva Esparta", weight: 150 }, { id: "VE-P", name: "Portuguesa" }, { id: "VE-R", name: "Sucre" }, { id: "VE-S", name: "Tachira" }, { id: "VE-T", name: "Trujillo" }, { id: "VE-U", name: "Yaracuy" }, { id: "VE-V", name: "Zulia" }, { id: "VE-W", name: "Vargas" }, { id: "VE-X", name: "Vargas" }, { id: "VE-Y", name: "Delta Amacuro" }, { id: "VE-Z", name: "Amazonas" }] },
    { code: "VN", name: "Vietnam", continent: "Asia", populationM: 99, economy: 58, infrastructure: 55, tourism: 78, significance: 58, divisions: [{ id: "VN-SG", name: "Ho Chi Minh City", weight: 160 }, { id: "VN-HN", name: "Hanoi", weight: 150 }, { id: "VN-DN", name: "Da Nang", weight: 145 }, { id: "VN-HP", name: "Hai Phong" }, { id: "VN-CT", name: "Can Tho" }, { id: "VN-QN", name: "Quang Ninh", weight: 130 }, { id: "VN-KH", name: "Khanh Hoa", weight: 135 }, { id: "VN-LD", name: "Lam Dong" }, { id: "VN-BD", name: "Binh Duong" }, { id: "VN-DN2", name: "Dong Nai" }, { id: "VN-BT", name: "Binh Thuan" }, { id: "VN-HU", name: "Hue" }] },
    { code: "ZA", name: "South Africa", continent: "Africa", populationM: 60, economy: 55, infrastructure: 58, tourism: 85, significance: 60, divisions: [{ id: "ZA-GP", name: "Gauteng", weight: 150 }, { id: "ZA-WC", name: "Western Cape", weight: 160 }, { id: "ZA-KZN", name: "KwaZulu-Natal", weight: 120 }, { id: "ZA-EC", name: "Eastern Cape" }, { id: "ZA-FS", name: "Free State" }, { id: "ZA-LP", name: "Limpopo" }, { id: "ZA-MP", name: "Mpumalanga" }, { id: "ZA-NC", name: "Northern Cape" }, { id: "ZA-NW", name: "North West" }] },
    { code: "ZM", name: "Zambia", continent: "Africa", populationM: 20, economy: 35, infrastructure: 32, tourism: 75, significance: 40, divisions: [{ id: "ZM-LS", name: "Lusaka", weight: 140 }, { id: "ZM-CO", name: "Copperbelt" }, { id: "ZM-SO", name: "Southern" }, { id: "ZM-CE", name: "Central" }, { id: "ZM-EA", name: "Eastern" }, { id: "ZM-NO", name: "Northern" }, { id: "ZM-NW", name: "North-Western" }, { id: "ZM-WE", name: "Western" }, { id: "ZM-LP", name: "Luapula" }, { id: "ZM-MU", name: "Muchinga" }] },
    { code: "ZW", name: "Zimbabwe", continent: "Africa", populationM: 16, economy: 32, infrastructure: 30, tourism: 85, significance: 40, divisions: [{ id: "ZW-HA", name: "Harare", weight: 140 }, { id: "ZW-BU", name: "Bulawayo" }, { id: "ZW-MN", name: "Matabeleland North" }, { id: "ZW-MS", name: "Matabeleland South" }, { id: "ZW-MW", name: "Mashonaland West" }, { id: "ZW-ME", name: "Mashonaland East" }, { id: "ZW-MC", name: "Mashonaland Central" }, { id: "ZW-MV", name: "Masvingo" }, { id: "ZW-MI", name: "Midlands" }, { id: "ZW-MA", name: "Manicaland" }] },
  ],
};
