/**
 * Pins the derivation against a vector generated by the canonical implementation.
 *
 * Be clear about what this does and does not prove.
 *
 * It DOES prove: the bundle in this app derives the same key and address the
 * canonical obsidian-core does, from the same words and the same indices. If a
 * dependency is upgraded, the sync drifts, or the indices change, this fails
 * loudly instead of silently producing a different wallet for the same phrase.
 *
 * It does NOT prove the canonical derivation is itself correct. The vector below
 * was generated FROM that implementation, so it cannot detect an error that is
 * already in it. obsidian-core's own test suite is what covers that; this file
 * covers only the question "does this app agree with the node?".
 *
 * That distinction is the whole reason this test exists separately. The failure
 * mode it guards against is the one the platform's wallet.ts documents from its own
 * 1.3.0 history: a derivation change that produced a different address for the same
 * 24 words, so a claim signed with it was refused by every node.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { deriveWallet, isValidRecoveryPhrase } from '../../obsidian-interface/web/core/crypto/mnemonic.js';
import { addressFromPublicKey } from '../../obsidian-interface/web/core/crypto/keys.js';

/** BIP-39's standard all-"abandon" phrase, so this vector is reproducible by
 *  anyone without inventing a secret of their own. */
const PHRASE =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';

/**
 * Generated by the canonical implementation:
 *   deriveWallet(PHRASE, 0, 0) -> addressFromPublicKey(publicKey)
 * on obsidian-core 1.6.1 with @noble/hashes 1.5.0 and @noble/curves 1.6.0.
 *
 * If this value ever changes, the derivation changed. Stop and find out why before
 * trusting any wallet this app produces.
 */
const EXPECTED_ADDRESS = 'obs13s4pgc4qczhgdjdmxhm8g9wf7e2ya66rxdgrkj';

test('the standard BIP-39 phrase derives the pinned address', () => {
  assert.equal(isValidRecoveryPhrase(PHRASE), true);
  const wallet = deriveWallet(PHRASE, 0, 0);
  assert.equal(addressFromPublicKey(wallet.publicKey), EXPECTED_ADDRESS);
});

test('the wallet object carries its own address, and it agrees', () => {
  const wallet = deriveWallet(PHRASE, 0, 0);
  assert.equal(wallet.address, EXPECTED_ADDRESS);
  assert.equal(wallet.address, addressFromPublicKey(wallet.publicKey));
});

test('derivation is deterministic across calls', () => {
  const a = deriveWallet(PHRASE, 0, 0);
  const b = deriveWallet(PHRASE, 0, 0);
  assert.equal(a.publicKey, b.publicKey);
  // `privateKey`, not `privateKeyHex`. This line used to compare two undefined
  // values, which passed no matter what the derivation did.
  assert.equal(a.privateKey, b.privateKey);
  assert.equal(typeof a.privateKey, 'string');
  assert.equal(a.privateKey.length, 64, 'a secp256k1 private key is 32 bytes of hex');
});

test('different indices derive a different wallet', () => {
  const first = deriveWallet(PHRASE, 0, 0);
  const second = deriveWallet(PHRASE, 0, 1);
  assert.notEqual(first.publicKey, second.publicKey);
  assert.notEqual(first.address, second.address);
});

test('an invalid phrase is refused before anything is derived', () => {
  assert.equal(isValidRecoveryPhrase('not a real recovery phrase at all'), false);
  assert.equal(isValidRecoveryPhrase('twelve words only here now'), false);
  assert.equal(isValidRecoveryPhrase(''), false);
});
