/**
 * Mining gate issuer keys.
 *
 * A MINING_CLAIM is valid only with a certificate signed by one of these keys (see mining/gate.ts). They are PUBLIC
 * keys, committed in the genesis document, hashed into the genesis id and into every state root. The private half
 * lives only on the account platform that issues certificates, in an encrypted keystore, and never in this repository.
 *
 * NOTHING IS COMMITTED YET FOR MAINNET OR TESTNET, ON PURPOSE
 *   The issuer key is the operators' power over who can mine, so it must be generated by the operators, on a machine
 *   they trust, and not by whoever wrote this file. Until a list is committed here:
 *     - a mainnet/testnet node takes the keys from `OBSIDIAN_MINING_GATE_PUBLIC_KEYS` (every node must use the same
 *       list; a different list is a different genesis id, so the nodes simply do not peer), and
 *     - with no keys at all, no claim can be accepted (the gate fails closed), so nobody mines and nobody is let in.
 *   To commit a list: `node scripts/generate-mining-gate-key.mjs`, paste the printed public key(s) below, rebuild, and
 *   publish the new genesis id. After that an override with a different list is refused, exactly like the bootstrap
 *   validator committee in bootstrap-keys.ts.
 *
 * STAGING / DEVNET
 *   Operators supply their own list with `OBSIDIAN_MINING_GATE_PUBLIC_KEYS`.
 */

import type { NetworkDefinition, NetworkName } from '../protocol/networks.js';

export type CommittedGateNetwork = Extract<NetworkName, 'mainnet' | 'testnet'>;

/** Canonical issuer key lists, lowercase compressed secp256k1 public keys, sorted. */
export const COMMITTED_MINING_GATE_KEYS: Readonly<Record<CommittedGateNetwork, readonly string[]>> = {
  mainnet: [],
  testnet: [],
};

export function committedMiningGateKeys(net: NetworkDefinition): readonly string[] {
  const committed = (COMMITTED_MINING_GATE_KEYS as Record<string, readonly string[] | undefined>)[net.name];
  return committed ?? [];
}
